/**
 * Pre-researched plant knowledge — structured gardening data for common garden plants.
 * This is the source of truth for the plant_entries table.
 * MiniMax can be used to extend or verify, but the core data lives here.
 *
 * Data sourced from: USDA zones, general gardening knowledge, Cornell Cooperative Extension,
 * Old Farmer's Almanac, and other reliable horticultural references.
 */

export interface PlantData {
  commonName: string;
  scientificName: string;
  variety?: string;
  category: 'vegetable' | 'fruit' | 'herb' | 'flower' | 'tree' | 'nut' | 'legume';
  family?: string;
  description?: string;
  sunlight?: string;
  waterNeeds?: string;
  soilType?: string;
  soilPh?: string;
  zoneMin?: number;
  zoneMax?: number;
  frostTolerance?: string;
  plantingDepth?: string;
  spacing?: string;
  daysToGermination?: number;
  daysToMaturity?: number;
  matureHeight?: string;
  matureSpread?: string;
  growthHabit?: string;
  perennialYears?: number | null;
  companionPlants?: string[];
  incompatiblePlants?: string[];
  commonPests?: string[];
  commonDiseases?: string[];
  harvestWindow?: string;
  harvestIndicators?: string;
  careNotes?: string;
}

export const PLANT_DATA: PlantData[] = [
  // ─── VEGETABLES ────────────────────────────────────────────────────────────
  {
    commonName: 'Roma Tomato',
    scientificName: 'Solanum lycopersicum',
    variety: 'Roma',
    category: 'vegetable',
    family: 'Solanaceae',
    description: 'Plum-shaped paste tomato known for meaty flesh and few seeds. Excellent for sauces, canning, and drying. Compact indeterminate vines.',
    sunlight: 'full sun',
    waterNeeds: 'consistent',
    soilType: 'well-draining',
    soilPh: '6.0-6.8',
    zoneMin: 3,
    zoneMax: 11,
    frostTolerance: 'none',
    plantingDepth: '1/4 inch',
    spacing: '24-36 inches',
    daysToGermination: 7,
    daysToMaturity: 75,
    matureHeight: '4-6 feet',
    matureSpread: '2-3 feet',
    growthHabit: 'bush',
    perennialYears: null,
    companionPlants: ['Basil', 'Carrot', 'Parsley', 'Marigold'],
    incompatiblePlants: ['Brassica', 'Fennel', 'Corn'],
    commonPests: ['Tomato Hornworm', 'Aphids', 'Whiteflies'],
    commonDiseases: ['Early Blight', 'Late Blight', 'Fusarium Wilt'],
    harvestWindow: 'July-September',
    harvestIndicators: 'Firm, deep red color, slight give when squeezed',
    careNotes: 'Stake or cage for support. Remove suckers for larger fruit. Mulch to retain moisture.',
  },
  {
    commonName: 'Cherry Tomato',
    scientificName: 'Solanum lycopersicum var. cerasiforme',
    category: 'vegetable',
    family: 'Solanaceae',
    description: 'Small, sweet tomatoes perfect for snacking and salads. Prolific producers on indeterminate vines. Easier to grow than larger varieties.',
    sunlight: 'full sun',
    waterNeeds: 'consistent',
    soilType: 'well-draining',
    soilPh: '6.0-6.8',
    zoneMin: 3,
    zoneMax: 11,
    frostTolerance: 'none',
    plantingDepth: '1/4 inch',
    spacing: '24-36 inches',
    daysToGermination: 7,
    daysToMaturity: 65,
    matureHeight: '6-8 feet',
    matureSpread: '2-3 feet',
    growthHabit: 'vine',
    perennialYears: null,
    companionPlants: ['Basil', 'Parsley', 'Marigold', 'Chives'],
    incompatiblePlants: ['Brassica', 'Fennel'],
    commonPests: ['Aphids', 'Whiteflies', 'Spider Mites'],
    commonDiseases: ['Blossom End Rot', 'Cracking', 'Fusarium Wilt'],
    harvestWindow: 'June-October',
    harvestIndicators: 'Full color, slight softness, easy release from stem',
    careNotes: 'Needs strong support or cage. Extremely prolific — harvest daily at peak.',
  },
  {
    commonName: 'Jalapeño Pepper',
    scientificName: 'Capsicum annuum',
    variety: 'Jalapeño',
    category: 'vegetable',
    family: 'Solanaceae',
    description: 'Medium-heat pepper, 2,500-8,000 Scoville units. Thick flesh excellent for roasting, stuffing, and salsas. Compact plants yield heavily.',
    sunlight: 'full sun',
    waterNeeds: 'moderate',
    soilType: 'well-draining',
    soilPh: '6.0-6.8',
    zoneMin: 4,
    zoneMax: 11,
    frostTolerance: 'none',
    plantingDepth: '1/4 inch',
    spacing: '18-24 inches',
    daysToGermination: 14,
    daysToMaturity: 80,
    matureHeight: '2-3 feet',
    matureSpread: '18-24 inches',
    growthHabit: 'bush',
    perennialYears: null,
    companionPlants: ['Basil', 'Tomato', 'Carrot', 'Onion'],
    incompatiblePlants: ['Fennel', 'Kohlrabi'],
    commonPests: ['Aphids', 'Pepper Maggot', 'Spider Mites'],
    commonDiseases: ['Phytophthora Blight', 'Bacterial Leaf Spot'],
    harvestWindow: 'July-September',
    harvestIndicators: 'Glossy dark green, firm, 2-3 inches long. Red when fully ripe (hotter).',
    careNotes: 'Start indoors 8-10 weeks before last frost. Hotter when harvested red.',
  },
  {
    commonName: 'Bell Pepper',
    scientificName: 'Capsicum annuum',
    variety: 'Bell',
    category: 'vegetable',
    family: 'Solanaceae',
    description: 'Sweet, thick-walled peppers perfect for fresh eating, stuffing, and roasting. Colors range from green to red, yellow, orange, and purple.',
    sunlight: 'full sun',
    waterNeeds: 'moderate',
    soilType: 'well-draining',
    soilPh: '6.0-6.8',
    zoneMin: 4,
    zoneMax: 11,
    frostTolerance: 'none',
    plantingDepth: '1/4 inch',
    spacing: '18-24 inches',
    daysToGermination: 14,
    daysToMaturity: 90,
    matureHeight: '2-3 feet',
    matureSpread: '18-24 inches',
    growthHabit: 'bush',
    perennialYears: null,
    companionPlants: ['Basil', 'Tomato', 'Carrot', 'Onion'],
    incompatiblePlants: ['Fennel', 'Kohlrabi'],
    commonPests: ['Aphids', 'Pepper Maggot', 'Slugs'],
    commonDiseases: ['Phytophthora Blight', 'Bacterial Leaf Spot', 'Blossom End Rot'],
    harvestWindow: 'July-September',
    harvestIndicators: 'Firm, thick walls, full size for variety. Color developed (green = immature, red/yellow/orange = ripe).',
    careNotes: 'Needs warmth — plant after soil warms. Colors develop as peppers ripen.',
  },
  {
    commonName: 'Cucumber',
    scientificName: 'Cucumis sativus',
    category: 'vegetable',
    family: 'Cucurbitaceae',
    description: 'Refreshing, high-water vegetable for fresh eating, pickling, and salads. Grows on vining or bush plants. Best trellised for straight fruit.',
    sunlight: 'full sun',
    waterNeeds: 'high',
    soilType: 'well-draining',
    soilPh: '6.0-7.0',
    zoneMin: 4,
    zoneMax: 11,
    frostTolerance: 'none',
    plantingDepth: '1 inch',
    spacing: '12-24 inches',
    daysToGermination: 7,
    daysToMaturity: 60,
    matureHeight: '6-8 feet (vine)',
    matureSpread: '2-4 feet',
    growthHabit: 'vine',
    perennialYears: null,
    companionPlants: ['Bean', 'Corn', 'Pea', 'Radish', 'Sunflower'],
    incompatiblePlants: ['Potato', 'Sage', 'Mint'],
    commonPests: ['Cucumber Beetle', 'Aphids', 'Spider Mites'],
    commonDiseases: ['Powdery Mildew', 'Downy Mildew', 'Bacterial Wilt'],
    harvestWindow: 'June-August',
    harvestIndicators: 'Firm, uniform color, expected size for variety. Overripe = seedy and bitter.',
    careNotes: 'Trellising improves air circulation and fruit quality. Pick frequently to encourage production.',
  },
  {
    commonName: 'Zucchini',
    scientificName: 'Cucurbita pepo',
    variety: 'Zucchini',
    category: 'vegetable',
    family: 'Cucurbitaceae',
    description: 'Prolific summer squash. Harvest young (6-8 inches) for tender skin and mild flavor. Can be grilled, sautéed, baked, or spiralized.',
    sunlight: 'full sun',
    waterNeeds: 'moderate',
    soilType: 'well-draining',
    soilPh: '6.0-7.5',
    zoneMin: 3,
    zoneMax: 11,
    frostTolerance: 'none',
    plantingDepth: '1 inch',
    spacing: '24-36 inches',
    daysToGermination: 7,
    daysToMaturity: 50,
    matureHeight: '2-3 feet',
    matureSpread: '3-4 feet',
    growthHabit: 'bush',
    perennialYears: null,
    companionPlants: ['Corn', 'Bean', 'Nasturtium', 'Radish'],
    incompatiblePlants: ['Potato'],
    commonPests: ['Squash Vine Borer', 'Squash Bug', 'Aphids'],
    commonDiseases: ['Powdery Mildew', 'Blossom End Rot'],
    harvestWindow: 'June-September',
    harvestIndicators: 'Small to medium size (6-10 inches), tender skin, firm flesh. Check daily — grows fast!',
    careNotes: 'One plant yields heavily. Check daily during peak season. Large zucchini are seedy and watery.',
  },
  {
    commonName: 'Sugar Snap Peas',
    scientificName: 'Pisum sativum var. macrocarpon',
    category: 'vegetable',
    family: 'Fabaceae',
    description: 'Sweet, crunchy pods eaten whole. Excellent fresh, in stir-fries, or salads. Vining variety needs support. Cool-season crop.',
    sunlight: 'full sun',
    waterNeeds: 'moderate',
    soilType: 'well-draining',
    soilPh: '6.0-7.5',
    zoneMin: 3,
    zoneMax: 11,
    frostTolerance: 'light',
    plantingDepth: '1-2 inches',
    spacing: '3-4 inches',
    daysToGermination: 10,
    daysToMaturity: 70,
    matureHeight: '6-8 feet (vine)',
    matureSpread: '6-8 inches',
    growthHabit: 'vine',
    perennialYears: null,
    companionPlants: ['Carrot', 'Corn', 'Cucumber', 'Radish', 'Bean'],
    incompatiblePlants: ['Onion', 'Garlic', 'Gladiolus'],
    commonPests: ['Pea Aphid', 'Pea Weevil', 'Slugs'],
    commonDiseases: ['Powdery Mildew', 'Pea Moth'],
    harvestWindow: 'May-July',
    harvestIndicators: 'Plump pods, peas visible but not oversized. Sweet when fresh.',
    careNotes: 'Direct sow in early spring as soon as soil can be worked. Needs trellis. Afternoon shade in warm climates.',
  },
  {
    commonName: 'Green Bean',
    scientificName: 'Phaseolus vulgaris',
    variety: 'Green Bean',
    category: 'vegetable',
    family: 'Fabaceae',
    description: 'Classic bush or pole bean. Fresh green beans freeze well and are excellent steamed, sautéed, or in casseroles. Nitrogen-fixing.',
    sunlight: 'full sun',
    waterNeeds: 'moderate',
    soilType: 'well-draining',
    soilPh: '6.0-7.0',
    zoneMin: 3,
    zoneMax: 11,
    frostTolerance: 'none',
    plantingDepth: '1 inch',
    spacing: '4-6 inches',
    daysToGermination: 8,
    daysToMaturity: 60,
    matureHeight: '18-24 inches (bush) / 6-8 feet (pole)',
    matureSpread: '6-8 inches',
    growthHabit: 'bush',
    perennialYears: null,
    companionPlants: ['Corn', 'Cucumber', 'Carrot', 'Celery', 'Potato'],
    incompatiblePlants: ['Onion', 'Garlic', 'Fennel', 'Sunflower'],
    commonPests: ['Mexican Bean Beetle', 'Aphids', 'Slugs'],
    commonDiseases: ['Bean Mosaic Virus', 'Anthracnose', 'Rust'],
    harvestWindow: 'June-August',
    harvestIndicators: 'Pods snap easily, seeds inside not yet bulging, firm texture.',
    careNotes: 'Direct sow after last frost. Bush beans = no support, concentrated harvest. Pole beans = longer harvest, need trellis.',
  },
  {
    commonName: 'Broccoli',
    scientificName: 'Brassica oleracea var. italica',
    category: 'vegetable',
    family: 'Brassicaceae',
    description: 'Cool-season brassica producing dense green florets. Excellent for steaming, roasting, and stir-fries. Produces side shoots after main harvest.',
    sunlight: 'full sun',
    waterNeeds: 'moderate',
    soilType: 'well-draining',
    soilPh: '6.0-7.0',
    zoneMin: 3,
    zoneMax: 10,
    frostTolerance: 'light',
    plantingDepth: '1/4 inch',
    spacing: '18-24 inches',
    daysToGermination: 7,
    daysToMaturity: 100,
    matureHeight: '2-3 feet',
    matureSpread: '18-24 inches',
    growthHabit: 'upright',
    perennialYears: null,
    companionPlants: ['Celery', 'Onion', 'Garlic', 'Chamomile', 'Dill'],
    incompatiblePlants: ['Tomato', 'Strawberry', 'Grape'],
    commonPests: ['Cabbage Worm', 'Aphids', 'Flea Beetle'],
    commonDiseases: ['Clubroot', 'Downy Mildew', 'Black Rot'],
    harvestWindow: 'April-June, September-November',
    harvestIndicators: 'Dense, firm, tight florets before yellow petals show. Side shoots continue producing.',
    careNotes: 'Start indoors or direct sow. Bolts in heat — spring/fall crop. Protect from cabbage worms.',
  },
  {
    commonName: 'Kale',
    scientificName: 'Brassica oleracea var. sabellica',
    category: 'vegetable',
    family: 'Brassicaceae',
    description: 'Hardy leafy green, sweeter after frost. Varieties include Lacinato (dinosaur), Curly, and Red Russian. Nutrient-dense superfood.',
    sunlight: 'full sun',
    waterNeeds: 'moderate',
    soilType: 'well-draining',
    soilPh: '6.0-7.5',
    zoneMin: 2,
    zoneMax: 11,
    frostTolerance: 'hardy',
    plantingDepth: '1/4 inch',
    spacing: '18-24 inches',
    daysToGermination: 7,
    daysToMaturity: 60,
    matureHeight: '18-30 inches',
    matureSpread: '12-18 inches',
    growthHabit: 'upright',
    perennialYears: null,
    companionPlants: ['Beet', 'Celery', 'Onion', 'Potato'],
    incompatiblePlants: ['Strawberry', 'Grape'],
    commonPests: ['Cabbage Worm', 'Aphids', 'Slugs'],
    commonDiseases: ['Clubroot', 'Black Rot'],
    harvestWindow: 'Year-round, peak winter',
    harvestIndicators: 'Outer leaves 8-10 inches, harvest from bottom up. Flavor improves after frost.',
    careNotes: 'Very cold-hardy. Flavor sweetens in cool weather. Harvest outer leaves to extend production.',
  },
  {
    commonName: 'Spinach',
    scientificName: 'Spinacia oleracea',
    category: 'vegetable',
    family: 'Amaranthaceae',
    description: 'Fast-growing cool-season leafy green. Excellent raw in salads or cooked. Rich in iron, calcium, and vitamins A, C.',
    sunlight: 'partial shade',
    waterNeeds: 'consistent',
    soilType: 'well-draining',
    soilPh: '6.5-7.5',
    zoneMin: 3,
    zoneMax: 11,
    frostTolerance: 'moderate',
    plantingDepth: '1/2 inch',
    spacing: '4-6 inches',
    daysToGermination: 7,
    daysToMaturity: 45,
    matureHeight: '8-12 inches',
    matureSpread: '6-8 inches',
    growthHabit: 'rosette',
    perennialYears: null,
    companionPlants: ['Strawberry', 'Radish', 'Pea', 'Bean'],
    incompatiblePlants: ['Fennel'],
    commonPests: ['Leaf Miners', 'Aphids', 'Slugs'],
    commonDiseases: ['Downy Mildew', 'Fusarium Wilt'],
    harvestWindow: 'March-June, September-November',
    harvestIndicators: 'Harvest outer leaves when 3-4 inches long, or cut entire plant at base.',
    careNotes: 'Bolts quickly in heat. Plant spring and fall. Succession plant every 2 weeks.',
  },
  {
    commonName: 'Lettuce',
    scientificName: 'Lactuca sativa',
    category: 'vegetable',
    family: 'Asteraceae',
    description: 'Fast-growing salad green. Varieties include Romaine, Butterhead, Iceberg, and Leaf. Best in cool weather. Cut-and-come-again harvest.',
    sunlight: 'partial shade',
    waterNeeds: 'consistent',
    soilType: 'well-draining',
    soilPh: '6.0-7.0',
    zoneMin: 3,
    zoneMax: 11,
    frostTolerance: 'light',
    plantingDepth: '1/4 inch',
    spacing: '6-12 inches',
    daysToGermination: 7,
    daysToMaturity: 45,
    matureHeight: '6-12 inches',
    matureSpread: '6-12 inches',
    growthHabit: 'rosette',
    perennialYears: null,
    companionPlants: ['Carrot', 'Radish', 'Strawberry', 'Chives'],
    incompatiblePlants: ['Fennel'],
    commonPests: ['Slugs', 'Aphids', 'Rabbits'],
    commonDiseases: ['Downy Mildew', 'Lettuce Drop', 'Tip Burn'],
    harvestWindow: 'April-July, September-October',
    harvestIndicators: 'Firm, full leaves before bolting. Bolting = bitter, sends up flower stalk.',
    careNotes: 'Succession plant every 2 weeks. Shade cloth in hot weather. Harvest in morning for crispness.',
  },
  {
    commonName: 'Carrot',
    scientificName: 'Daucus carota',
    category: 'vegetable',
    family: 'Apiaceae',
    description: 'Sweet root vegetable, excellent raw or cooked. Requires loose, deep soil for straight roots. High in beta carotene and fiber.',
    sunlight: 'full sun',
    waterNeeds: 'moderate',
    soilType: 'loamy',
    soilPh: '6.0-6.8',
    zoneMin: 3,
    zoneMax: 11,
    frostTolerance: 'light',
    plantingDepth: '1/4 inch',
    spacing: '2-3 inches',
    daysToGermination: 14,
    daysToMaturity: 75,
    matureHeight: '8-12 inches',
    matureSpread: '2-3 inches',
    growthHabit: 'upright',
    perennialYears: null,
    companionPlants: ['Onion', 'Leeks', 'Rosemary', 'Sage', 'Tomato'],
    incompatiblePlants: ['Dill', 'Fennel', 'Parsnip'],
    commonPests: ['Carrot Rust Fly', 'Wireworms', 'Nematodes'],
    commonDiseases: ['Carrot Root Rot', 'Leaf Blight'],
    harvestWindow: 'Year-round (spring planting)',
    harvestIndicators: 'Shoulders visible at soil line, 3/4 to 1 inch diameter. Loosen soil before pulling.',
    careNotes: 'Direct sow only — dislikes transplanting. Keep soil moist until germination. Thin seedlings early.',
  },
  {
    commonName: 'Garlic',
    scientificName: 'Allium sativum',
    category: 'vegetable',
    family: 'Amaryllidaceae',
    description: 'Fall-planted bulb. Hardneck varieties produce scapes in spring. Excellent for cooking, medicinal use, and pest deterrent in garden.',
    sunlight: 'full sun',
    waterNeeds: 'low',
    soilType: 'well-draining',
    soilPh: '6.0-7.0',
    zoneMin: 3,
    zoneMax: 10,
    frostTolerance: 'hardy',
    plantingDepth: '2 inches',
    spacing: '6-8 inches',
    daysToGermination: 14,
    daysToMaturity: 240,
    matureHeight: '2-3 feet',
    matureSpread: '6-8 inches',
    growthHabit: 'upright',
    perennialYears: null,
    companionPlants: ['Tomato', 'Pepper', 'Carrot', 'Rose'],
    incompatiblePlants: ['Bean', 'Pea', 'Asparagus', 'Strawberry'],
    commonPests: ['Garlic Mosaic Virus', 'Nematodes', 'Thrips'],
    commonDiseases: ['White Rot', 'Rust', 'Penicillium Clove Rot'],
    harvestWindow: 'July-August',
    harvestIndicators: 'Lower leaves brown, upper leaves still green, bulbs well-formed with tight wrappers.',
    careNotes: 'Plant in fall for summer harvest. Hardneck = cold-hardy, produces scapes. Softneck = better storage.',
  },
  {
    commonName: 'Potato',
    scientificName: 'Solanum tuberosum',
    category: 'vegetable',
    family: 'Solanaceae',
    description: 'Starchy tuber, fourth largest food crop globally. Grows from seed potatoes. Excellent baked, mashed, fried, or roasted.',
    sunlight: 'full sun',
    waterNeeds: 'consistent',
    soilType: 'well-draining',
    soilPh: '5.0-6.5',
    zoneMin: 3,
    zoneMax: 11,
    frostTolerance: 'none',
    plantingDepth: '4 inches',
    spacing: '12 inches',
    daysToGermination: 14,
    daysToMaturity: 120,
    matureHeight: '2-3 feet',
    matureSpread: '18-24 inches',
    growthHabit: 'upright',
    perennialYears: null,
    companionPlants: ['Bean', 'Corn', 'Cabbage', 'Horseradish'],
    incompatiblePlants: ['Tomato', 'Cucumber', 'Pumpkin', 'Sunflower'],
    commonPests: ['Colorado Potato Beetle', 'Aphids', 'Wireworms'],
    commonDiseases: ['Late Blight', 'Early Blight', 'Scab'],
    harvestWindow: 'July-September',
    harvestIndicators: "Foliage dies back, skins set (don't rub off). Dig carefully to avoid damage.",
    careNotes: 'Hill soil around stems as they grow to prevent green tubers. Never eat green potatoes (toxic solanine).',
  },
  {
    commonName: 'Corn',
    scientificName: 'Zea mays',
    category: 'vegetable',
    family: 'Poaceae',
    description: 'Wind-pollinated grain. Plant in blocks, not rows, for even pollination. Sweet corn is excellent fresh, frozen, or grilled.',
    sunlight: 'full sun',
    waterNeeds: 'high',
    soilType: 'well-draining',
    soilPh: '5.8-7.0',
    zoneMin: 3,
    zoneMax: 11,
    frostTolerance: 'none',
    plantingDepth: '1-2 inches',
    spacing: '9-12 inches',
    daysToGermination: 10,
    daysToMaturity: 90,
    matureHeight: '6-8 feet',
    matureSpread: '12-18 inches',
    growthHabit: 'upright',
    perennialYears: null,
    companionPlants: ['Bean', 'Squash', 'Cucumber', 'Pea'],
    incompatiblePlants: ['Tomato', 'Celery'],
    commonPests: ['Corn Earworm', 'Corn Borer', 'Armyworm'],
    commonDiseases: ['Common Rust', 'Southern Corn Leaf Blight', 'Maize Dwarf Mosaic'],
    harvestWindow: 'July-August',
    harvestIndicators: 'Silks brown and dry, kernels release milky juice when punctured, cobs lean away from stalk.',
    careNotes: 'Plant in blocks (min 4 rows) for pollination. No succession planting — single large planting. Harvest immediately for best sweetness.',
  },
  {
    commonName: 'Eggplant',
    scientificName: 'Solanum melongena',
    category: 'vegetable',
    family: 'Solanaceae',
    description: 'Heat-loving plant with glossy purple, white, or striped fruit. Meatly texture for grilling, roasting, and curries. Also called aubergine.',
    sunlight: 'full sun',
    waterNeeds: 'moderate',
    soilType: 'well-draining',
    soilPh: '5.5-6.5',
    zoneMin: 5,
    zoneMax: 11,
    frostTolerance: 'none',
    plantingDepth: '1/4 inch',
    spacing: '24-30 inches',
    daysToGermination: 14,
    daysToMaturity: 80,
    matureHeight: '2-4 feet',
    matureSpread: '18-24 inches',
    growthHabit: 'bush',
    perennialYears: null,
    companionPlants: ['Bean', 'Pepper', 'Spinach', 'Thyme'],
    incompatiblePlants: ['Fennel'],
    commonPests: ['Flea Beetles', 'Colorado Potato Beetle', 'Aphids'],
    commonDiseases: ['Verticillium Wilt', 'Phomopsis Blight'],
    harvestWindow: 'July-September',
    harvestIndicators: 'Glossy skin, firm flesh, seeds white (not brown). Overripe = dull skin, seedy.',
    careNotes: 'Needs warm soil — plant after tomatoes. Drought stress causes bitter fruit. Harvest frequently.',
  },
  // ─── HERBS ─────────────────────────────────────────────────────────────────
  {
    commonName: 'Basil',
    scientificName: 'Ocimum basilicum',
    category: 'herb',
    family: 'Lamiaceae',
    description: 'Warm-season culinary herb. Sweet basil is the classic for Italian pesto and tomato dishes. Highly frost-sensitive.',
    sunlight: 'full sun',
    waterNeeds: 'moderate',
    soilType: 'well-draining',
    soilPh: '6.0-7.0',
    zoneMin: 4,
    zoneMax: 11,
    frostTolerance: 'none',
    plantingDepth: '1/4 inch',
    spacing: '12-18 inches',
    daysToGermination: 7,
    daysToMaturity: 60,
    matureHeight: '18-24 inches',
    matureSpread: '12-18 inches',
    growthHabit: 'bush',
    perennialYears: null,
    companionPlants: ['Tomato', 'Pepper', 'Oregano'],
    incompatiblePlants: ['Sage', 'Rue'],
    commonPests: ['Japanese Beetle', 'Aphids', 'Slugs'],
    commonDiseases: ['Fusarium Wilt', 'Downy Mildew', 'Gray Mold'],
    harvestWindow: 'June-September',
    harvestIndicators: 'Harvest before flowering. Pinch from top to encourage bushiness. Morning harvest = best oil content.',
    careNotes: 'Pinch flowers to prolong leaf production. Very frost-sensitive — bring indoors or succession plant.',
  },
  {
    commonName: 'Mint',
    scientificName: 'Mentha',
    category: 'herb',
    family: 'Lamiaceae',
    description: 'Vigorous, spreading perennial herb. Spearmint and peppermint are most common. Excellent for tea, cocktails, and desserts.',
    sunlight: 'partial shade',
    waterNeeds: 'high',
    soilType: 'well-draining',
    soilPh: '6.0-7.5',
    zoneMin: 3,
    zoneMax: 9,
    frostTolerance: 'hardy',
    plantingDepth: '1/4 inch',
    spacing: '18-24 inches',
    daysToGermination: 14,
    daysToMaturity: 90,
    matureHeight: '12-24 inches',
    matureSpread: 'indefinite (spreads)',
    growthHabit: 'trailing',
    perennialYears: 5,
    companionPlants: ['Cabbage', 'Tomato', 'Peas'],
    incompatiblePlants: ['Chamomile'],
    commonPests: ['Mint Rust', 'Spider Mites', 'Whitefly'],
    commonDiseases: ['Mint Rust', 'Verticillium Wilt', 'Powdery Mildew'],
    harvestWindow: 'May-October',
    harvestIndicators: 'Harvest before flowering. Cut stems, strip leaves. Dry or use fresh.',
    careNotes: 'CONTAIN OR IT SPREADS — plant in buried pot or container. Very aggressive grower. Cut back hard in spring.',
  },
  {
    commonName: 'Rosemary',
    scientificName: 'Salvia rosmarinus',
    category: 'herb',
    family: 'Lamiaceae',
    description: 'Woody perennial herb with needle-like leaves. Mediterranean origin — loves heat and drought. Used in roasting, breads, and as ornamental.',
    sunlight: 'full sun',
    waterNeeds: 'low',
    soilType: 'well-draining',
    soilPh: '6.0-7.0',
    zoneMin: 7,
    zoneMax: 11,
    frostTolerance: 'light',
    plantingDepth: '1/4 inch',
    spacing: '24-36 inches',
    daysToGermination: 21,
    daysToMaturity: 180,
    matureHeight: '3-5 feet',
    matureSpread: '2-4 feet',
    growthHabit: 'upright',
    perennialYears: 10,
    companionPlants: ['Sage', 'Thyme', 'Lavender', 'Bean', 'Cabbage'],
    incompatiblePlants: ['Pumpkin', 'Cucumber'],
    commonPests: ['Spider Mites', 'Mealybugs', 'Powdery Mildew'],
    commonDiseases: ['Root Rot', 'Powdery Mildew'],
    harvestWindow: 'Year-round',
    harvestIndicators: 'Harvest stems as needed. Best flavor just before flowering. Cut no more than 1/3 of plant at once.',
    careNotes: 'Needs excellent drainage. Wet roots = death. Can overwinter indoors in cold climates. Very drought-tolerant once established.',
  },
  {
    commonName: 'Thyme',
    scientificName: 'Thymus vulgaris',
    category: 'herb',
    family: 'Lamiaceae',
    description: 'Low-growing perennial herb with tiny aromatic leaves. Excellent for French cuisine, roasting, and seasoning blends. Also used as ground cover.',
    sunlight: 'full sun',
    waterNeeds: 'low',
    soilType: 'well-draining',
    soilPh: '6.0-8.0',
    zoneMin: 4,
    zoneMax: 9,
    frostTolerance: 'moderate',
    plantingDepth: 'surface sow (needs light)',
    spacing: '12-18 inches',
    daysToGermination: 21,
    daysToMaturity: 95,
    matureHeight: '6-12 inches',
    matureSpread: '12-18 inches',
    growthHabit: 'trailing',
    perennialYears: 5,
    companionPlants: ['Cabbage', 'Eggplant', 'Potato', 'Strawberry'],
    incompatiblePlants: [],
    commonPests: ['Spider Mites', 'Root Rot (in wet soil)'],
    commonDiseases: ['Root Rot', 'Botrytis'],
    harvestWindow: 'Year-round (spring-summer peak)',
    harvestIndicators: 'Harvest before flowering, cut stems in morning. Thrives from repeated harvesting.',
    careNotes: 'Loves heat and poor soil. Excellent drainage required. Shear after flowering to maintain shape.',
  },
  {
    commonName: 'Cilantro',
    scientificName: 'Coriandrum sativum',
    category: 'herb',
    family: 'Apiaceae',
    description: 'Fast-growing annual herb. Leaves (cilantro) and seeds (coriander) both used. Essential in Mexican, Indian, and Thai cuisine.',
    sunlight: 'partial shade',
    waterNeeds: 'moderate',
    soilType: 'well-draining',
    soilPh: '6.2-6.8',
    zoneMin: 3,
    zoneMax: 11,
    frostTolerance: 'light',
    plantingDepth: '1/4 inch',
    spacing: '2-4 inches',
    daysToGermination: 7,
    daysToMaturity: 50,
    matureHeight: '12-24 inches',
    matureSpread: '6-12 inches',
    growthHabit: 'upright',
    perennialYears: null,
    companionPlants: ['Spinach', 'Tomato', 'Pepper', 'Bean'],
    incompatiblePlants: ['Fennel'],
    commonPests: ['Aphids', 'Leafhoppers', 'Slugs'],
    commonDiseases: ['Powdery Mildew', 'Bacterial Leaf Spot'],
    harvestWindow: 'April-June, September-October',
    harvestIndicators: 'Cut outer leaves when 6 inches. Bolts quickly in heat — grow in shade or succession plant.',
    careNotes: 'Bolts in heat — plant early spring or fall. Let some go to seed for coriander. Self-sows readily.',
  },
  {
    commonName: 'Parsley',
    scientificName: 'Petroselinum crispum',
    category: 'herb',
    family: 'Apiaceae',
    description: 'Biennial herb, flat-leaf (Italian) or curly varieties. Fresh garnish and culinary seasoning. High in vitamin C and iron.',
    sunlight: 'partial shade',
    waterNeeds: 'moderate',
    soilType: 'well-draining',
    soilPh: '6.0-7.0',
    zoneMin: 4,
    zoneMax: 11,
    frostTolerance: 'moderate',
    plantingDepth: '1/4 inch',
    spacing: '6-8 inches',
    daysToGermination: 21,
    daysToMaturity: 75,
    matureHeight: '12-18 inches',
    matureSpread: '6-12 inches',
    growthHabit: 'upright',
    perennialYears: null,
    companionPlants: ['Tomato', 'Asparagus', 'Corn', 'Pepper'],
    incompatiblePlants: ['Lettuce', 'Mint'],
    commonPests: ['Parsley Worm', 'Aphids', 'Leaf Miners'],
    commonDiseases: ['Crown Rot', 'Leaf Blight'],
    harvestWindow: 'Year-round',
    harvestIndicators: 'Cut outer stems at base. Flavor intensifies after light frost.',
    careNotes: 'Slow to germinate — soak seeds overnight. Biennial: first year = leaves, second year = flowers/seeds.',
  },
  // ─── FRUITS ────────────────────────────────────────────────────────────────
  {
    commonName: 'Strawberry',
    scientificName: 'Fragaria × ananassa',
    category: 'fruit',
    family: 'Rosaceae',
    description: 'Perennial berry, spreads by runners. June-bearing, everbearing, and day-neutral varieties. Excellent fresh, frozen, or in jam.',
    sunlight: 'full sun',
    waterNeeds: 'consistent',
    soilType: 'well-draining',
    soilPh: '5.5-6.5',
    zoneMin: 3,
    zoneMax: 10,
    frostTolerance: 'moderate',
    plantingDepth: 'crown at soil level',
    spacing: '12-18 inches',
    daysToGermination: 0,
    daysToMaturity: 365,
    matureHeight: '6-12 inches',
    matureSpread: '12-24 inches',
    growthHabit: 'trailing',
    perennialYears: 5,
    companionPlants: ['Bean', 'Lettuce', 'Onion', 'Spinach', 'Thyme'],
    incompatiblePlants: ['Cabbage', 'Broccoli', 'Cauliflower'],
    commonPests: ['Slugs', 'Birds', 'Spider Mites', 'Aphids'],
    commonDiseases: ['Gray Mold', 'Powdery Mildew', 'Verticillium Wilt'],
    harvestWindow: 'May-August (year 2+)',
    harvestIndicators: 'Fully red, glossy, fragrant. Pick with stem attached. Harvest in morning.',
    careNotes: 'Remove runners for larger fruit. Mulch to keep fruit clean and retain moisture. Renew beds every 3-4 years.',
  },
  {
    commonName: 'Blueberry',
    scientificName: 'Vaccinium corymbosum',
    category: 'fruit',
    family: 'Ericaceae',
    description: 'Long-lived deciduous shrub. Requires acidic soil (pH 4.5-5.5). High in antioxidants. Plant 2+ varieties for cross-pollination.',
    sunlight: 'full sun',
    waterNeeds: 'consistent',
    soilType: 'well-draining',
    soilPh: '4.5-5.5',
    zoneMin: 3,
    zoneMax: 9,
    frostTolerance: 'hardy',
    plantingDepth: 'crown 1 inch below soil',
    spacing: '4-6 feet',
    daysToGermination: 0,
    daysToMaturity: 1095,
    matureHeight: '4-8 feet',
    matureSpread: '4-8 feet',
    growthHabit: 'upright',
    perennialYears: 30,
    companionPlants: ['Strawberry', 'Rhododendron', 'Azalea'],
    incompatiblePlants: [],
    commonPests: ['Birds', 'Spotted Wing Drosophila', 'Aphids'],
    commonDiseases: ['Mummy Berry', 'Botrytis Blight', 'Phomopsis Canker'],
    harvestWindow: 'June-August (year 3+)',
    harvestIndicators: 'Deep blue color, easy release, sweet-tart taste. Ripe berries fall into your hand.',
    careNotes: 'Requires acidic soil — use pine bark mulch or sulfur. Prune older canes annually. Needs 2 varieties for best yields.',
  },
  {
    commonName: 'Raspberry',
    scientificName: 'Rubus idaeus',
    category: 'fruit',
    family: 'Rosaceae',
    description: 'Perennial bramble producing red, black, or gold berries. Primocane vs floricane types determine harvest timing. Excellent fresh and frozen.',
    sunlight: 'full sun',
    waterNeeds: 'moderate',
    soilType: 'well-draining',
    soilPh: '6.0-7.0',
    zoneMin: 3,
    zoneMax: 9,
    frostTolerance: 'hardy',
    plantingDepth: 'crown 1-2 inches below soil',
    spacing: '18-24 inches',
    daysToGermination: 0,
    daysToMaturity: 730,
    matureHeight: '5-8 feet',
    matureSpread: '3-4 feet',
    growthHabit: 'upright',
    perennialYears: 10,
    companionPlants: ['Garlic', 'Marigold', 'Nasturtium'],
    incompatiblePlants: ['Potato', 'Tomato', 'Eggplant', 'Pepper'],
    commonPests: ['Japanese Beetle', 'Raspberry Crown Borer', 'Aphids'],
    commonDiseases: ['Anthracnose', 'Cane Blight', 'Phytophthora Root Rot'],
    harvestWindow: 'June-October (variety-dependent)',
    harvestIndicators: 'Bright color, easy release from cane. Pick gently to avoid crushing.',
    careNotes: 'Support with trellis or wire. Prune spent floricanes to ground after harvest. Root suckers spread — contain or thin.',
  },
  // ─── FLOWERS ───────────────────────────────────────────────────────────────
  {
    commonName: 'Sunflower',
    scientificName: 'Helianthus annuus',
    category: 'flower',
    family: 'Asteraceae',
    description: 'Tall annual flower with large seed heads. Edible seeds, attracts pollinators and birds. Excellent for cut flowers and succession planting.',
    sunlight: 'full sun',
    waterNeeds: 'low',
    soilType: 'well-draining',
    soilPh: '6.0-7.5',
    zoneMin: 2,
    zoneMax: 11,
    frostTolerance: 'none',
    plantingDepth: '1 inch',
    spacing: '6-24 inches',
    daysToGermination: 10,
    daysToMaturity: 90,
    matureHeight: '3-12 feet',
    matureSpread: '6-24 inches',
    growthHabit: 'upright',
    perennialYears: null,
    companionPlants: ['Cucumber', 'Corn', 'Squash', 'Bean'],
    incompatiblePlants: ['Potato'],
    commonPests: ['Sunflower Moth', 'Birds', 'Squirrels'],
    commonDiseases: ['Downy Mildew', 'Rust', 'Sclerotinia Head Rot'],
    harvestWindow: 'July-September',
    harvestIndicators: 'Back of head brown, seeds loose and dark-striped. Cut head and dry before seed removal.',
    careNotes: 'Direct sow after frost. May need staking. Succession plant every 2 weeks for continuous blooms.',
  },
  {
    commonName: 'Marigold',
    scientificName: 'Tagetes',
    category: 'flower',
    family: 'Asteraceae',
    description: 'Hardy annual with pungent scent that repels many garden pests. Excellent companion plant, border plant, and cut flower.',
    sunlight: 'full sun',
    waterNeeds: 'low',
    soilType: 'well-draining',
    soilPh: '6.0-7.5',
    zoneMin: 2,
    zoneMax: 11,
    frostTolerance: 'none',
    plantingDepth: '1/4 inch',
    spacing: '8-12 inches',
    daysToGermination: 7,
    daysToMaturity: 60,
    matureHeight: '6-36 inches',
    matureSpread: '6-12 inches',
    growthHabit: 'bush',
    perennialYears: null,
    companionPlants: ['Tomato', 'Pepper', 'Bean', 'Cucumber', 'Squash'],
    incompatiblePlants: ['Bean', 'Cabbage'],
    commonPests: ['Slugs', 'Aphids', 'Spider Mites'],
    commonDiseases: ['Root Rot', 'Fusarium Wilt'],
    harvestWindow: 'June-October',
    harvestIndicators: 'Deadhead spent blooms to encourage continuous flowering. Harvest flowers when fully open.',
    careNotes: 'African marigolds (T. erecta) = tall, large blooms. French marigolds (T. patula) = compact, pest-repelling. Tagetes roots repel nematodes.',
  },
  {
    commonName: 'Lavender',
    scientificName: 'Lavandula',
    category: 'flower',
    family: 'Lamiaceae',
    description: 'Fragrant perennial Mediterranean herb. Excellent for borders, containers, and cut flowers. Dried flowers used in crafts and aromatherapy.',
    sunlight: 'full sun',
    waterNeeds: 'low',
    soilType: 'well-draining',
    soilPh: '6.5-8.0',
    zoneMin: 5,
    zoneMax: 9,
    frostTolerance: 'moderate',
    plantingDepth: 'surface sow (needs light)',
    spacing: '18-24 inches',
    daysToGermination: 21,
    daysToMaturity: 365,
    matureHeight: '1-3 feet',
    matureSpread: '2-4 feet',
    growthHabit: 'bush',
    perennialYears: 10,
    companionPlants: ['Rosemary', 'Thyme', 'Sage', 'Echinacea'],
    incompatiblePlants: ['Mint'],
    commonPests: ['Root Rot (in wet soil)', 'Spittlebugs'],
    commonDiseases: ['Root Rot', 'Septoria Leaf Spot'],
    harvestWindow: 'June-August',
    harvestIndicators: 'Cut when buds color but before fully open. Harvest in morning after dew dries.',
    careNotes: 'NEVER overwater. Excellent drainage is critical. Prune hard each spring. English lavender = most cold-hardy.',
  },
  // ─── LEGUMES ───────────────────────────────────────────────────────────────
  {
    commonName: 'Lima Bean',
    scientificName: 'Phaseolus lunatus',
    category: 'legume',
    family: 'Fabaceae',
    description: 'Warm-season bean, also called butter bean. Large, creamy beans for succotash, soups, and casseroles. Pole or bush varieties.',
    sunlight: 'full sun',
    waterNeeds: 'moderate',
    soilType: 'well-draining',
    soilPh: '6.0-7.0',
    zoneMin: 4,
    zoneMax: 11,
    frostTolerance: 'none',
    plantingDepth: '1-2 inches',
    spacing: '4-6 inches',
    daysToGermination: 10,
    daysToMaturity: 90,
    matureHeight: '6-12 feet (pole) / 2 feet (bush)',
    matureSpread: '6-12 inches',
    growthHabit: 'vine',
    perennialYears: null,
    companionPlants: ['Corn', 'Cucumber', 'Squash', 'Carrot'],
    incompatiblePlants: ['Onion', 'Garlic', 'Fennel', 'Sunflower'],
    commonPests: ['Lima Bean Pod Borer', 'Aphids', 'Mexican Bean Beetle'],
    commonDiseases: ['Mosaic Virus', 'Anthracnose', 'Downy Mildew'],
    harvestWindow: 'August-September',
    harvestIndicators: 'Pods plump, beans visible through pod. Green for fresh use, tan/dry for shell beans.',
    careNotes: 'Needs warm soil (60°F+). Pole types need support. Fresh limas are toxic if raw — always cook.',
  },
];
