/**
 * Step 1: Clean up existing data before the variety @@unique constraint.
 *
 * Problem: @@unique([scientificName]) meant only 1 record per species existed.
 * The variety seeder was overwriting the same record for each variety of a species.
 *
 * Solution: For each scientificName that has a base record (variety=NULL or empty)
 * AND variety-specific records trying to be added — keep BOTH as separate records.
 *
 * This script:
 * - Finds all species that need variety-specific records
 * - Duplicates the base record for each variety, then sets the variety field
 *
 * Run: cd green-thumb && ./node_modules/.bin/tsx scripts/seed-varieties.ts
 */

const { PrismaClient } = await import('@prisma/client')
const { Prisma } = await import('@prisma/client')
const prisma = new PrismaClient()

// ── The full variety dataset ──────────────────────────────────────────────────
const VARIETIES: Array<{
  commonName: string; scientificName: string; variety: string; category: string; family: string
  description: string; chillHours?: string; harvestWindow?: string; pollination?: string
  sunlight?: string; waterNeeds?: string; zoneMin?: number; zoneMax?: number
  matureHeight?: string; growthHabit?: string; perennialYears?: number
  companionPlants?: string[]; incompatiblePlants?: string[]; commonPests?: string[]
  careNotes?: string
}> = [
  // ── Figs ──────────────────────────────────────────────────────────────────
  { commonName: 'Brown Turkey Fig', scientificName: 'Ficus carica', variety: 'Brown Turkey', family: 'Moraceae', category: 'fruit', description: 'Hardy, prolific breba crop fig. Medium-large, brownish-purple fruit with pink flesh. Excellent for fresh eating and preserves.', chillHours: '100-200', harvestWindow: 'July-August (breba), September-October (main)', pollination: 'Self-fertile', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 7, zoneMax: 10, matureHeight: '3-5m / 10-16ft', growthHabit: 'spreading', perennialYears: 3, companionPlants: ['Strawberry', 'Grape', 'Blueberry'], incompatiblePlants: [], commonPests: ['Fig beetle', 'Rust mite'], careNotes: 'Prune to open center. In zones 7-8, protect young wood from hard frost.' },
  { commonName: 'Celeste Fig', scientificName: 'Ficus carica', variety: 'Celeste', family: 'Moraceae', category: 'fruit', description: 'Small to medium violet-brown fig with very sweet amber flesh. One of the coldest-hardy figs. Closed-eye fruit resists souring.', chillHours: '100-200', harvestWindow: 'July-August', pollination: 'Self-fertile', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 6, zoneMax: 10, matureHeight: '3-4m / 10-13ft', growthHabit: 'upright', perennialYears: 3, companionPlants: ['Strawberry', 'Grape'], incompatiblePlants: [], commonPests: ['Fig beetle'], careNotes: 'Excellent for cold climates. Celeste tends to be smaller and more compact than other figs.' },
  { commonName: 'Chicago Cold Hardy Fig', scientificName: 'Ficus carica', variety: 'Chicago Cold Hardy', family: 'Moraceae', category: 'fruit', description: 'Bred in Chicago, this is one of the most cold-hardy figs. Purple-bronze fruit with sweet strawberry-colored flesh.', chillHours: '100-200', harvestWindow: 'August-September', pollination: 'Self-fertile', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 5, zoneMax: 9, matureHeight: '2.5-4m / 8-13ft', growthHabit: 'spreading', perennialYears: 3, companionPlants: ['Strawberry', 'Blueberry'], incompatiblePlants: [], commonPests: ['Fig beetle'], careNotes: 'Dies back to ground in zones 5-6 but re-grows from roots. Fruit on new wood.' },
  { commonName: 'Kadota Fig', scientificName: 'Ficus carica', variety: 'Kadota', family: 'Moraceae', category: 'fruit', description: 'Ancient Italian variety. Medium, greenish-yellow fig with amber flesh. Very sweet and excellent for drying and fresh eating.', chillHours: '100-200', harvestWindow: 'August-September (main crop)', pollination: 'Self-fertile', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 7, zoneMax: 10, matureHeight: '3-5m / 10-16ft', growthHabit: 'spreading', perennialYears: 3, companionPlants: ['Strawberry', 'Grape'], incompatiblePlants: [], commonPests: ['Fig beetle', 'Souring bacteria'], careNotes: 'Closed-eye variety resists souring. Needs heat for main crop — best in warm microclimates.' },
  { commonName: 'Violette Fig', scientificName: 'Ficus carica', variety: 'Violette', family: 'Moraceae', category: 'fruit', description: 'French variety with small to medium violet-purple fruit. Rich, sweet dark flesh. Excellent fresh or preserved.', chillHours: '100-200', harvestWindow: 'July-August (breba), August-September (main)', pollination: 'Self-fertile', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 7, zoneMax: 10, matureHeight: '3-5m / 10-16ft', growthHabit: 'spreading', perennialYears: 3, companionPlants: ['Strawberry', 'Grape', 'Blueberry'], incompatiblePlants: [], commonPests: ['Fig beetle'], careNotes: 'Traditional French variety. Needs a warm, sheltered spot in marginal zones.' },
  { commonName: 'LSU Purple Fig', scientificName: 'Ficus carica', variety: 'LSU Purple', family: 'Moraceae', category: 'fruit', description: 'LSU release with medium purple fruit and red flesh. Very sweet, mild flavor. Heavy producer.', chillHours: '100-200', harvestWindow: 'July-September', pollination: 'Self-fertile', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 7, zoneMax: 10, matureHeight: '3-4m / 10-13ft', growthHabit: 'upright', perennialYears: 3, companionPlants: ['Strawberry', 'Grape'], incompatiblePlants: [], commonPests: ['Fig beetle', 'Nematodes'], careNotes: 'LSU Purple is vigorous and productive. Bred for Gulf Coast conditions.' },
  { commonName: 'Alma Fig', scientificName: 'Ficus carica', variety: 'Alma', family: 'Moraceae', category: 'fruit', description: 'Texas A&M release. Small, brownish-gold fig with amber flesh. Extremely sweet with caramel notes.', chillHours: '100-200', harvestWindow: 'August-October', pollination: 'Self-fertile', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 8, zoneMax: 10, matureHeight: '3-4m / 10-13ft', growthHabit: 'upright', perennialYears: 3, companionPlants: ['Strawberry', 'Grape'], incompatiblePlants: [], commonPests: ['Fig beetle'], careNotes: 'Bred in Texas for heat tolerance. Excellent for the South.' },
  { commonName: 'Magnolia Fig', scientificName: 'Ficus carica', variety: 'Magnolia', family: 'Moraceae', category: 'fruit', description: 'Large, brownish-purple fruit with pink flesh. Classic Southern variety. Very productive and reliable.', chillHours: '100-200', harvestWindow: 'July-September', pollination: 'Self-fertile', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 7, zoneMax: 10, matureHeight: '3-5m / 10-16ft', growthHabit: 'spreading', perennialYears: 3, companionPlants: ['Strawberry', 'Grape', 'Blueberry'], incompatiblePlants: [], commonPests: ['Fig beetle'], careNotes: 'Classic Gulf Coast variety. The famous "Celeste" cousin.' },
  { commonName: 'Olympian Fig', scientificName: 'Ficus carica', variety: 'Olympian', family: 'Moraceae', category: 'fruit', description: 'Cold-hardy fig from the Pacific Northwest. Large, greenish-purple fruit with darkruby flesh. Sweeter than many cold-hardy varieties.', chillHours: '100-200', harvestWindow: 'August-September', pollination: 'Self-fertile', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 6, zoneMax: 9, matureHeight: '3-4m / 10-13ft', growthHabit: 'spreading', perennialYears: 3, companionPlants: ['Strawberry', 'Blueberry'], incompatiblePlants: [], commonPests: ['Fig beetle'], careNotes: 'One of the sweetest cold-hardy figs. Bred in Washington State.' },
  { commonName: 'Desert King Fig', scientificName: 'Ficus carica', variety: 'Desert King', family: 'Moraceae', category: 'fruit', description: 'Large, greenish-yellow fruit with strawberry-colored flesh. Excellent fresh eating. Best in hot, dry climates.', chillHours: '100-200', harvestWindow: 'July-August (breba only)', pollination: 'Self-fertile', sunlight: 'full sun', waterNeeds: 'low', zoneMin: 7, zoneMax: 10, matureHeight: '3-4m / 10-13ft', growthHabit: 'spreading', perennialYears: 3, companionPlants: ['Strawberry', 'Grape'], incompatiblePlants: [], commonPests: ['Fig beetle'], careNotes: 'Known for its breba crop (no pollination needed). Needs dry heat for best fruit quality.' },
  { commonName: 'Panache Tiger Fig', scientificName: 'Ficus carica', variety: 'Panache Tiger', family: 'Moraceae', category: 'fruit', description: 'Stunning striped green and yellow fig with bright red flesh. Also called "Panaché" or "Tiger Fig". Highly ornamental fruit.', chillHours: '100-200', harvestWindow: 'August-September', pollination: 'Self-fertile', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 7, zoneMax: 10, matureHeight: '3-4m / 10-13ft', growthHabit: 'upright', perennialYears: 3, companionPlants: ['Strawberry', 'Grape'], incompatiblePlants: [], commonPests: ['Fig beetle'], careNotes: 'Eye is fairly open — protect from rain/souring. The most beautiful fig for fresh eating.' },
  { commonName: 'Negronne Fig', scientificName: 'Ficus carica', variety: 'Negronne', family: 'Moraceae', category: 'fruit', description: 'Small to medium dark purple fig with very sweet, rich red flesh. French variety known for intense flavor.', chillHours: '100-200', harvestWindow: 'July-September', pollination: 'Self-fertile', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 7, zoneMax: 10, matureHeight: '2.5-3.5m / 8-11ft', growthHabit: 'upright', perennialYears: 3, companionPlants: ['Strawberry', 'Grape', 'Blueberry'], incompatiblePlants: [], commonPests: ['Fig beetle'], careNotes: 'Compact growth makes it good for containers. Often called "Violette" in the US.' },

  // ── Apples ─────────────────────────────────────────────────────────────────
  { commonName: 'Honeycrisp Apple', scientificName: 'Malus domestica', variety: 'Honeycrisp', family: 'Rosaceae', category: 'fruit', description: 'University of Minnesota introduction. Exceptional storage life and very crisp, juicy texture. Excellent sweet-tart balance.', chillHours: '800-1000', harvestWindow: 'September-October', pollination: 'Requires pollinizer (Granny Smith, Fuji)', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 3, zoneMax: 7, matureHeight: '4-6m / 12-20ft', growthHabit: 'upright', perennialYears: 5, companionPlants: ['Chives', 'Nasturtium', 'Comfrey', 'Clover'], incompatiblePlants: ['Walnut', 'Grass'], commonPests: ['Apple maggot', 'codling moth', 'fire blight'], careNotes: 'Moderate vigor. Pre-harvest drop can be an issue — harvest promptly. Resistant to scab.' },
  { commonName: 'Fuji Apple', scientificName: 'Malus domestica', variety: 'Fuji', family: 'Rosaceae', category: 'fruit', description: 'Japanese cross of Red Delicious × Ralls Janet. Very sweet, crisp, and juicy. Excellent keeper with outstanding flavor.', chillHours: '350-400', harvestWindow: 'October', pollination: 'Requires pollinizer (Honeycrisp, Gala)', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 5, zoneMax: 8, matureHeight: '4-6m / 12-20ft', growthHabit: 'upright', perennialYears: 5, companionPlants: ['Chives', 'Nasturtium', 'Comfrey', 'Clover'], incompatiblePlants: ['Walnut', 'Grass'], commonPests: ['Apple maggot', 'codling moth', 'fire blight'], careNotes: 'Vigorous, productive. Long storage life — keeps months in refrigeration.' },
  { commonName: 'Gala Apple', scientificName: 'Malus domestica', variety: 'Gala', family: 'Rosaceae', category: 'fruit', description: 'New Zealand introduction. Mild, sweet, aromatic. Fine-textured flesh. Excellent for fresh eating and sauces.', chillHours: '500-600', harvestWindow: 'September', pollination: 'Requires pollinizer (Fuji, Honeycrisp)', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 5, zoneMax: 8, matureHeight: '3-5m / 10-16ft', growthHabit: 'upright', perennialYears: 5, companionPlants: ['Chives', 'Nasturtium', 'Comfrey', 'Clover'], incompatiblePlants: ['Walnut', 'Grass'], commonPests: ['Apple maggot', 'codling moth', 'fire blight'], careNotes: 'Moderately vigorous, early bearing. Thin fruit for larger apples.' },
  { commonName: 'Granny Smith Apple', scientificName: 'Malus domestica', variety: 'Granny Smith', family: 'Rosaceae', category: 'fruit', description: 'Australian chance seedling. Bright green, very tart and crisp. Excellent for baking and fresh eating. Very long storage life.', chillHours: '600-700', harvestWindow: 'October-November', pollination: 'Requires pollinizer (Gala, Fuji)', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 6, zoneMax: 9, matureHeight: '4-6m / 12-20ft', growthHabit: 'spreading', perennialYears: 5, companionPlants: ['Chives', 'Nasturtium', 'Comfrey', 'Clover'], incompatiblePlants: ['Walnut', 'Grass'], commonPests: ['Apple maggot', 'codling moth', 'fire blight'], careNotes: 'Very vigorous and productive. Holds fruit well into winter. Good pollinizer for many varieties.' },
  { commonName: 'Pink Lady Apple', scientificName: 'Malus domestica', variety: 'Pink Lady', family: 'Rosaceae', category: 'fruit', description: 'Australian Cripps Pink. Pinkish-orange blush over yellow. Sweet-tart with effervescent texture. Excellent keeper.', chillHours: '600-700', harvestWindow: 'Late October-November', pollination: 'Requires pollinizer (Gala, Fuji)', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 6, zoneMax: 9, matureHeight: '4-6m / 12-20ft', growthHabit: 'upright', perennialYears: 5, companionPlants: ['Chives', 'Nasturtium', 'Comfrey', 'Clover'], incompatiblePlants: ['Walnut', 'Grass'], commonPests: ['Apple maggot', 'codling moth', 'fire blight'], careNotes: 'Low vigor on semi-dwarfing rootstock. Hang time is critical — harvest at full maturity.' },
  { commonName: 'Golden Delicious Apple', scientificName: 'Malus domestica', variety: 'Golden Delicious', family: 'Rosaceae', category: 'fruit', description: 'Mutant of Grimes Golden. Sweet, mellow, juicy. Excellent fresh eating and for salads. Good pollinizer.', chillHours: '600-700', harvestWindow: 'September-October', pollination: 'Self-fertile (but better with pollinizer)', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 5, zoneMax: 8, matureHeight: '4-6m / 12-20ft', growthHabit: 'upright', perennialYears: 5, companionPlants: ['Chives', 'Nasturtium', 'Comfrey', 'Clover'], incompatiblePlants: ['Walnut', 'Grass'], commonPests: ['Apple maggot', 'codling moth', 'fire blight'], careNotes: 'Vigorous, productive. Must be thinned to avoid biennial bearing. Skin is tender — bruise easily.' },
  { commonName: 'Red Delicious Apple', scientificName: 'Malus domestica', variety: 'Red Delicious', family: 'Rosaceae', category: 'fruit', description: 'Most widely planted apple in the US. Sweet, mild. Distinctive elongated shape with thick skin.', chillHours: '700-800', harvestWindow: 'September-October', pollination: 'Requires pollinizer (Gala, Fuji, Golden)', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 5, zoneMax: 8, matureHeight: '4-6m / 12-20ft', growthHabit: 'upright', perennialYears: 5, companionPlants: ['Chives', 'Nasturtium', 'Comfrey', 'Clover'], incompatiblePlants: ['Walnut', 'Grass'], commonPests: ['Apple maggot', 'codling moth', 'fire blight'], careNotes: 'Moderately vigorous. Noted for biennial bearing — thin consistently.' },
  { commonName: 'Braeburn Apple', scientificName: 'Malus domestica', variety: 'Braeburn', family: 'Rosaceae', category: 'fruit', description: 'New Zealand variety. Sweet-tart, very aromatic, firm. Excellent for fresh eating, baking, and long storage.', chillHours: '700-800', harvestWindow: 'October', pollination: 'Requires pollinizer (Fuji, Gala)', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 5, zoneMax: 8, matureHeight: '4-6m / 12-20ft', growthHabit: 'upright', perennialYears: 5, companionPlants: ['Chives', 'Nasturtium', 'Comfrey', 'Clover'], incompatiblePlants: ['Walnut', 'Grass'], commonPests: ['Apple maggot', 'codling moth', 'fire blight', 'bitter pit'], careNotes: 'Vigorous, productive. Susceptible to bitter pit — maintain calcium through the season.' },
  { commonName: 'McIntosh Apple', scientificName: 'Malus domestica', variety: 'McIntosh', family: 'Rosaceae', category: 'fruit', description: 'Canadian heirloom. White flesh, tender, very juicy. Sweet-tart aromatic flavor. Classic for applesauce.', chillHours: '700-900', harvestWindow: 'September', pollination: 'Requires pollinizer (Honeycrisp, Gala)', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 4, zoneMax: 7, matureHeight: '4-6m / 12-20ft', growthHabit: 'spreading', perennialYears: 5, companionPlants: ['Chives', 'Nasturtium', 'Comfrey', 'Clover'], incompatiblePlants: ['Walnut', 'Grass'], commonPests: ['Apple maggot', 'codling moth', 'fire blight'], careNotes: 'Susceptible to scab. Not a good keeper — use promptly after harvest.' },
  { commonName: 'Mutsu Crispin Apple', scientificName: 'Malus domestica', variety: 'Mutsu (Crispin)', family: 'Rosaceae', category: 'fruit', description: 'Japanese triploid. Very large, greenish-yellow. Firm, sweet, low acid. Excellent fresh or for baking. Known as Crispin in the US.', chillHours: '600-700', harvestWindow: 'October', pollination: 'Self-sterile — needs pollinizer', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 5, zoneMax: 8, matureHeight: '4-6m / 12-20ft', growthHabit: 'upright', perennialYears: 5, companionPlants: ['Chives', 'Nasturtium', 'Comfrey', 'Clover'], incompatiblePlants: ['Walnut', 'Grass'], commonPests: ['Apple maggot', 'codling moth', 'fire blight'], careNotes: 'Very vigorous. Triploid — poor pollenizer and needs a pollinizer itself.' },

  // ── Stone Fruits ───────────────────────────────────────────────────────────
  { commonName: 'Santa Rosa Plum', scientificName: 'Prunus salicina', variety: 'Santa Rosa', family: 'Rosaceae', category: 'fruit', description: 'Japanese plum. Reddish-purple skin with amber flesh. Sweet, tangy, aromatic. Excellent fresh eating and for canning.', chillHours: '300-400', harvestWindow: 'June-July', pollination: 'Self-fertile', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 5, zoneMax: 9, matureHeight: '3-5m / 10-16ft', growthHabit: 'spreading', perennialYears: 4, companionPlants: ['Grape', 'Strawberry', 'Comfrey', 'Clover'], incompatiblePlants: [], commonPests: ['Brown rot', 'Japanese beetle', 'aphids'], careNotes: 'Productive and reliable. Thin fruit for larger plums. Santa Rosa is a good pollinizer for other Japanese plums.' },
  { commonName: 'Italian Prune Plum', scientificName: 'Prunus domestica', variety: 'Italian Prune', family: 'Rosaceae', category: 'fruit', description: 'European prune plum. Oval, dark purple with sweet, firm, freestone flesh. Excellent for drying (prunes), fresh eating, and baking.', chillHours: '800-1000', harvestWindow: 'September', pollination: 'Self-fertile', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 5, zoneMax: 8, matureHeight: '3-5m / 10-16ft', growthHabit: 'upright', perennialYears: 4, companionPlants: ['Grape', 'Strawberry', 'Comfrey', 'Clover'], incompatiblePlants: [], commonPests: ['Brown rot', 'Japanese beetle'], careNotes: 'Upright growth habit. Very productive. Often needs less thinning than Japanese plums.' },
  { commonName: 'Elberta Peach', scientificName: 'Prunus persica', variety: 'Elberta', family: 'Rosaceae', category: 'fruit', description: 'Classic American peach. Large, yellow-fleshed freestone. Sweet, aromatic, excellent for fresh eating, canning, and freezing.', chillHours: '800-1000', harvestWindow: 'August (mid-late)', pollination: 'Self-fertile', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 5, zoneMax: 9, matureHeight: '3-5m / 10-16ft', growthHabit: 'spreading', perennialYears: 3, companionPlants: ['Grape', 'Strawberry', 'Comfrey', 'Nasturtium'], incompatiblePlants: [], commonPests: ['Brown rot', 'peach tree borer', 'leaf curl'], careNotes: 'Reliable and productive. Needs annual pruning to maintain vigor. Susceptible to leaf curl — apply dormant spray.' },
  { commonName: 'Reliance Peach', scientificName: 'Prunus persica', variety: 'Reliance', family: 'Rosaceae', category: 'fruit', description: 'University of New Hampshire release. One of the hardiest peaches. Medium fruit with yellow flesh. Freestone. Good for fresh eating and freezing.', chillHours: '800-1000', harvestWindow: 'August', pollination: 'Self-fertile', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 4, zoneMax: 8, matureHeight: '3-5m / 10-16ft', growthHabit: 'spreading', perennialYears: 3, companionPlants: ['Grape', 'Strawberry', 'Comfrey', 'Nasturtium'], incompatiblePlants: [], commonPests: ['Brown rot', 'peach tree borer', 'leaf curl'], careNotes: 'Hardiest quality peach for northern gardens. Produces reliably where other peaches fail.' },
  { commonName: 'Frost Peach', scientificName: 'Prunus persica', variety: 'Frost', family: 'Rosaceae', category: 'fruit', description: 'University of California release with excellent leaf curl resistance. Red-blushed fruit with white flesh. Mild, sweet, freestone.', chillHours: '300-400', harvestWindow: 'July-August', pollination: 'Self-fertile', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 6, zoneMax: 9, matureHeight: '3-5m / 10-16ft', growthHabit: 'spreading', perennialYears: 3, companionPlants: ['Grape', 'Strawberry', 'Comfrey', 'Nasturtium'], incompatiblePlants: [], commonPests: ['Brown rot', 'peach tree borer', 'leaf curl'], careNotes: 'Bred for the Pacific Northwest where leaf curl is prevalent. Excellent disease resistance.' },
  { commonName: 'Bing Cherry', scientificName: 'Prunus avium', variety: 'Bing', family: 'Rosaceae', category: 'fruit', description: 'The classic sweet cherry. Large, dark mahogany fruit with firm, sweet flesh. Excellent fresh eating. The standard for commercial sweet cherries.', chillHours: '700-1000', harvestWindow: 'June-July', pollination: 'Requires pollinizer (Van, Lambert, or Royal Ann)', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 5, zoneMax: 8, matureHeight: '5-8m / 16-26ft', growthHabit: 'upright', perennialYears: 4, companionPlants: ['Grape', 'Comfrey', 'Clover', 'Nasturtium'], incompatiblePlants: [], commonPests: ['Birds', 'cherry fruit fly', 'brown rot'], careNotes: 'Large tree — needs space. Netting essential for bird protection. Crack-resistant skin.' },
  { commonName: 'Montmorency Cherry', scientificName: 'Prunus cerasus', variety: 'Montmorency', family: 'Rosaceae', category: 'fruit', description: 'The classic American pie cherry. Bright red skin with yellow flesh. Tart, firm, excellent for pies, preserves, and drying.', chillHours: '500-700', harvestWindow: 'June-July', pollination: 'Self-fertile', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 4, zoneMax: 8, matureHeight: '3-5m / 10-16ft', growthHabit: 'spreading', perennialYears: 4, companionPlants: ['Grape', 'Comfrey', 'Clover', 'Nasturtium'], incompatiblePlants: [], commonPests: ['Birds', 'cherry fruit fly', 'brown rot'], careNotes: 'More cold-hardy than sweet cherries. Compact growth. Birds are the main pest — netting required.' },
  { commonName: 'Goldcot Apricot', scientificName: 'Prunus armeniaca', variety: 'Goldcot', family: 'Rosaceae', category: 'fruit', description: 'Hardy apricot bred for northern climates. Medium fruit with orange skin and firm, freestone flesh. Good for fresh eating and preserves.', chillHours: '600-900', harvestWindow: 'July', pollination: 'Self-fertile', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 5, zoneMax: 8, matureHeight: '3-5m / 10-16ft', growthHabit: 'upright', perennialYears: 4, companionPlants: ['Grape', 'Strawberry', 'Comfrey', 'Clover'], incompatiblePlants: [], commonPests: ['Brown rot', 'Japanese beetle', 'peach tree borer'], careNotes: 'Hardier than most apricots. Blooms early — frost is the main risk in cold climates.' },
  { commonName: 'Stark Saturn Donut Peach', scientificName: 'Prunus persica', variety: 'Stark Saturn Donut', family: 'Rosaceae', category: 'fruit', description: 'Unique flat, donut-shaped peach. White flesh with sweet, mild flavor. Clingstone. Very ornamental tree.', chillHours: '300-400', harvestWindow: 'July-August', pollination: 'Self-fertile', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 5, zoneMax: 9, matureHeight: '3-4m / 10-13ft', growthHabit: 'spreading', perennialYears: 3, companionPlants: ['Grape', 'Strawberry', 'Comfrey', 'Nasturtium'], incompatiblePlants: [], commonPests: ['Brown rot', 'peach tree borer', 'leaf curl'], careNotes: 'Novelty variety with ornamental appeal. Flat shape makes it easier to pick. Excellent for kids.' },
  { commonName: 'Lazy Lady Apricot', scientificName: 'Prunus armeniaca', variety: 'Lazy Lady', family: 'Rosaceae', category: 'fruit', description: 'Bred for late bloom to avoid frost. Compact, productive, and self-fertile. Sweet, rich apricot flavor.', chillHours: '600-900', harvestWindow: 'July-August', pollination: 'Self-fertile', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 5, zoneMax: 8, matureHeight: '2-3m / 6-10ft', growthHabit: 'upright', perennialYears: 4, companionPlants: ['Grape', 'Strawberry', 'Comfrey', 'Clover'], incompatiblePlants: [], commonPests: ['Brown rot', 'Japanese beetle'], careNotes: 'Late-blooming makes it more reliable in marginal climates. Compact tree, good for small gardens.' },

  // ── Berries ────────────────────────────────────────────────────────────────
  { commonName: 'Duke Blueberry', scientificName: 'Vaccinium corymbosum', variety: 'Duke', family: 'Ericaceae', category: 'fruit', description: 'Early-season northern highbush. Large, firm berries with mild, sweet flavor. Upright, vigorous growth. Excellent commercial variety.', chillHours: '800-1000', harvestWindow: 'June-July (early)', pollination: 'Self-fertile (better with pollinizer)', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 4, zoneMax: 7, matureHeight: '1.5-2m / 5-6ft', growthHabit: 'upright', perennialYears: 3, companionPlants: ['Strawberry', 'Cranberry', 'Lingonberry', 'Rhododendron'], incompatiblePlants: [], commonPests: ['Birds', 'blueberry maggot', 'mummy berry'], careNotes: 'Early bloom means frost risk in cold climates. Acid soil (pH 4.5-5.5) essential.' },
  { commonName: 'Pink Lemonade Blueberry', scientificName: 'Vaccinium corymbosum', variety: 'Pink Lemonade', family: 'Ericaceae', category: 'fruit', description: 'Unique pink blueberry! Glossy, pinkish-red fruit turns deeper pink when fully ripe. Mild, sweet flavor. ornamental value as well.', chillHours: '300-400', harvestWindow: 'July-August', pollination: 'Self-fertile (better with pollinizer)', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 5, zoneMax: 10, matureHeight: '1.5-2m / 5-6ft', growthHabit: 'upright', perennialYears: 3, companionPlants: ['Strawberry', 'Cranberry', 'Lingonberry'], incompatiblePlants: [], commonPests: ['Birds', 'blueberry maggot'], careNotes: 'Novelty and ornamental. Berries turn pink before fully ripe — wait for deeper color for best sweetness.' },
  { commonName: 'Sunshine Blue Blueberry', scientificName: 'Vaccinium corymbosum', variety: 'Sunshine Blue', family: 'Ericaceae', category: 'fruit', description: 'Compact, semi-dwarf southern highbush. Medium berries with excellent flavor. Self-fertile and ornamental with pink flowers.', chillHours: '150-200', harvestWindow: 'June-August', pollination: 'Self-fertile', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 5, zoneMax: 10, matureHeight: '1-1.5m / 3-5ft', growthHabit: 'compact', perennialYears: 3, companionPlants: ['Strawberry', 'Cranberry', 'Lingonberry'], incompatiblePlants: [], commonPests: ['Birds', 'blueberry maggot'], careNotes: 'Great for containers and small spaces. Low chill requirement — good for mild winters.' },
  { commonName: 'Prelude Raspberry', scientificName: 'Rubus idaeus', variety: 'Prelude', family: 'Rosaceae', category: 'fruit', description: 'Early primocane raspberry from Cornell. Fruit is medium-sized, firm, with good flavor. Very early — extends the season.', chillHours: '800-1000', harvestWindow: 'June-July (very early primocane)', pollination: 'Self-fertile', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 3, zoneMax: 8, matureHeight: '1.2-1.8m / 4-6ft', growthHabit: 'upright', perennialYears: 2, companionPlants: ['Garlic', 'Chives', 'Tansy', 'Yarrow'], incompatiblePlants: [], commonPests: ['Raspberry crown borer', 'spider mites', 'Japanese beetle'], careNotes: 'Primocane — fruits on first-year canes. Cut all canes to ground in winter.' },
  { commonName: 'Heritage Raspberry', scientificName: 'Rubus idaeus', variety: 'Heritage', family: 'Rosaceae', category: 'fruit', description: 'The most popular primocane raspberry. Medium-large, firm, bright red berries. Excellent flavor. Very productive.', chillHours: '800-1000', harvestWindow: 'July-August (primocane), September-October (floricane)', pollination: 'Self-fertile', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 3, zoneMax: 8, matureHeight: '1.5-2m / 5-6ft', growthHabit: 'upright', perennialYears: 2, companionPlants: ['Garlic', 'Chives', 'Tansy', 'Yarrow'], incompatiblePlants: [], commonPests: ['Raspberry crown borer', 'spider mites', 'Japanese beetle'], careNotes: 'Primocane type — fruits on new canes. Cut to ground in winter. Can produce on floricanes too in mild climates.' },
  { commonName: 'Black Satin Blackberry', scientificName: 'Rubus fruticosus', variety: 'Black Satin', family: 'Rosaceae', category: 'fruit', description: 'Thornless, semi-erect blackberry. Large, firm, glossy black berries with sweet-tart flavor. Heavy producer.', chillHours: '200-400', harvestWindow: 'July-August', pollination: 'Self-fertile', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 5, zoneMax: 9, matureHeight: '2-3m / 6-10ft', growthHabit: 'semi-erect', perennialYears: 3, companionPlants: ['Garlic', 'Chives', 'Tansy', 'Yarrow'], incompatiblePlants: [], commonPests: ['Japanese beetle', 'spider mites', 'anthracnose'], careNotes: 'Thornless! Train to wire trellis. Primocane-fruiting on new canes.' },
  { commonName: 'Triple Crown Thornless Blackberry', scientificName: 'Rubus fruticosus', variety: 'Triple Crown Thornless', family: 'Rosaceae', category: 'fruit', description: 'Popular thornless variety. Large, firm, very sweet berries. Named for three "crowns" of superior characteristics: flavor, productivity, and vigor.', chillHours: '200-400', harvestWindow: 'July-August', pollination: 'Self-fertile', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 5, zoneMax: 9, matureHeight: '2-3m / 6-10ft', growthHabit: 'semi-erect', perennialYears: 3, companionPlants: ['Garlic', 'Chives', 'Tansy', 'Yarrow'], incompatiblePlants: [], commonPests: ['Japanese beetle', 'spider mites', 'anthracnose'], careNotes: 'Thornless. Vigorous grower — give ample space. Excellent fresh eating and for preserves.' },
  { commonName: 'Boysenberry', scientificName: 'Rubus idaeus', variety: 'Boysenberry', family: 'Rosaceae', category: 'fruit', description: 'Hybrid of raspberry, blackberry, and dewberry. Large, reddish-purple berries with unique sweet-tart flavor. Excellent for fresh eating, juice, and preserves.', chillHours: '200-400', harvestWindow: 'June-July', pollination: 'Self-fertile', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 5, zoneMax: 9, matureHeight: '2-3m / 6-10ft', growthHabit: 'trailing', perennialYears: 3, companionPlants: ['Garlic', 'Chives', 'Tansy'], incompatiblePlants: [], commonPests: ['Japanese beetle', 'bramble fruit worm', 'anthracnose'], careNotes: 'Trailing type — needs trellis. Was nearly extinct until revived by Knott\'s Berry Farm.' },
  { commonName: 'Marionberry', scientificName: 'Rubus idaeus', variety: 'Marionberry', family: 'Rosaceae', category: 'fruit', description: 'The "Cabernet of blackberries." Medium-large, shiny black berries with complex, rich flavor. Excellent for fresh eating, baking, and wine.', chillHours: '200-400', harvestWindow: 'July-August', pollination: 'Self-fertile', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 6, zoneMax: 9, matureHeight: '2-3m / 6-10ft', growthHabit: 'trailing', perennialYears: 3, companionPlants: ['Garlic', 'Chives', 'Tansy'], incompatiblePlants: [], commonPests: ['Japanese beetle', 'spider mites', 'anthracnose'], careNotes: 'Trailing — needs trellis support. Oregon\'s state berry. Very aromatic with complex flavor.' },
  { commonName: 'Invicta Gooseberry', scientificName: 'Ribes uva-crispa', variety: 'Invicta', family: 'Grossulariaceae', category: 'fruit', description: 'Large, pale green gooseberry with sweet flavor when ripe. Excellent for pies, jams, and fresh eating. Mildew-resistant.', chillHours: '800-1000', harvestWindow: 'July-August', pollination: 'Self-fertile', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 3, zoneMax: 8, matureHeight: '1-1.5m / 3-5ft', growthHabit: 'shrub', perennialYears: 4, companionPlants: ['Chives', 'Garlic', 'Tansy', 'Comfrey'], incompatiblePlants: [], commonPests: ['Gooseberry sawfly', 'powdery mildew', 'currant worm'], careNotes: 'Spines make harvesting tricky. Invicta is one of the most disease-resistant gooseberry varieties.' },
  { commonName: 'Red Lake Currant', scientificName: 'Ribes rubrum', variety: 'Red Lake', family: 'Grossulariaceae', category: 'fruit', description: 'Large, bright red currants on long strigs. Excellent for jelly, juice, and fresh eating. Very productive and hardy.', chillHours: '800-1000', harvestWindow: 'July', pollination: 'Self-fertile', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 3, zoneMax: 8, matureHeight: '1.5-2m / 5-6ft', growthHabit: 'shrub', perennialYears: 4, companionPlants: ['Chives', 'Garlic', 'Tansy', 'Comfrey'], incompatiblePlants: [], commonPests: ['Currant sawfly', 'aphids', 'leaf spot'], careNotes: 'Hardy and productive. Currants are self-fertile. Prune older canes annually to encourage new growth.' },
  { commonName: 'Adams Elderberry', scientificName: 'Sambucus nigra', variety: 'Adams', family: 'Adoxaceae', category: 'fruit', description: 'Large, productive American elderberry. Creamy-white flower clusters in spring. Dark purple berries for pies, wines, and medicinal use.', chillHours: '400-800', harvestWindow: 'August-September', pollination: 'Requires pollinizer (Johns or York)', sunlight: 'full sun', waterNeeds: 'high', zoneMin: 3, zoneMax: 9, matureHeight: '2-3m / 6-10ft', growthHabit: 'shrub', perennialYears: 4, companionPlants: ['Comfrey', 'Clover', 'Grape'], incompatiblePlants: [], commonPests: ['Elder borer', 'Japanese beetle', 'birds'], careNotes: 'Plant in pairs for cross-pollination. Berries must be cooked — raw elderberries are toxic. Excellent for guild planting.' },

  // ── Other Fruits ───────────────────────────────────────────────────────────
  { commonName: 'Bartlett Pear', scientificName: 'Pyrus communis', variety: 'Bartlett', family: 'Rosaceae', category: 'fruit', description: 'The world\'s most popular pear. Yellow-green fruit with sweet, buttery, aromatic flesh. Excellent for fresh eating, canning, and perry.', chillHours: '600-800', harvestWindow: 'August-September', pollination: 'Requires pollinizer (Bosc, Anjou)', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 5, zoneMax: 8, matureHeight: '4-6m / 12-20ft', growthHabit: 'spreading', perennialYears: 4, companionPlants: ['Comfrey', 'Clover', 'Nasturtium', 'Chives'], incompatiblePlants: ['Walnut'], commonPests: ['Fire blight', 'pear psylla', 'codling moth'], careNotes: 'Watch for fire blight in humid climates. Thin fruit for larger pears. Pick slightly green and ripen indoors.' },
  { commonName: 'Hosui Asian Pear', scientificName: 'Pyrus pyrifolia', variety: 'Hosui', family: 'Rosaceae', category: 'fruit', description: 'Brown-russeted Asian pear with exceptionally sweet, juicy, refreshing flesh. Crisp like an apple. Heavy bearing.', chillHours: '300-500', harvestWindow: 'August (early Asian pear)', pollination: 'Self-fertile (better with pollinizer)', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 5, zoneMax: 9, matureHeight: '4-6m / 12-20ft', growthHabit: 'upright', perennialYears: 4, companionPlants: ['Comfrey', 'Clover', 'Nasturtium', 'Chives'], incompatiblePlants: ['Walnut'], commonPests: ['Fire blight', 'pear psylla', 'codling moth'], careNotes: 'Does not need thinning as much as other Asian pears. Excellent fresh eating — crisp texture.' },
  { commonName: 'Kieffer Pear', scientificName: 'Pyrus communis', variety: 'Kieffer', family: 'Rosaceae', category: 'fruit', description: 'Hybrid of Asian and European pear. Hard, coarse flesh — best cooked or for preserves. Very hardy and disease-resistant.', chillHours: '300-400', harvestWindow: 'September-October', pollination: 'Self-fertile', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 4, zoneMax: 9, matureHeight: '4-6m / 12-20ft', growthHabit: 'spreading', perennialYears: 4, companionPlants: ['Comfrey', 'Clover', 'Nasturtium', 'Chives'], incompatiblePlants: ['Walnut'], commonPests: ['Fire blight (resistant)', 'pear psylla'], careNotes: 'Very hardy and low-chill. Great for baking and pear preserves. Tree is vigorous and productive.' },
  { commonName: 'Seckel Pear', scientificName: 'Pyrus communis', variety: 'Seckel', family: 'Rosaceae', category: 'fruit', description: 'Small, sweet, brownish-red pear. Known as the "sugar pear" — one of the sweetest. Excellent for fresh eating and preserves.', chillHours: '800-1000', harvestWindow: 'September-October', pollination: 'Requires pollinizer (Bartlett, Bosc)', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 5, zoneMax: 8, matureHeight: '3-5m / 10-16ft', growthHabit: 'spreading', perennialYears: 4, companionPlants: ['Comfrey', 'Clover', 'Nasturtium', 'Chives'], incompatiblePlants: ['Walnut'], commonPests: ['Fire blight', 'pear psylla'], careNotes: 'Compact tree — good for small gardens. Pick when green and ripen indoors. Highly disease-resistant.' },
  { commonName: 'D\'Anjou Pear', scientificName: 'Pyrus communis', variety: 'D\'Anjou', family: 'Rosaceae', category: 'fruit', description: 'Green, buttery French pear. Sweet, juicy, excellent for fresh eating and baking. Good keeper. Needs pollinizer.', chillHours: '600-800', harvestWindow: 'September-October', pollination: 'Requires pollinizer (Bartlett, Bosc)', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 5, zoneMax: 8, matureHeight: '4-6m / 12-20ft', growthHabit: 'spreading', perennialYears: 4, companionPlants: ['Comfrey', 'Clover', 'Nasturtium', 'Chives'], incompatiblePlants: ['Walnut'], commonPests: ['Fire blight', 'pear psylla', 'codling moth'], careNotes: 'Long storage life. Green when ripe — does not change color significantly. Store in fridge.' },
  { commonName: 'Fuyu Persimmon', scientificName: 'Diospyros kaki', variety: 'Fuyu', family: 'Ebenaceae', category: 'fruit', description: 'Non-astringent persimmon. Tomato-shaped, bright orange fruit. Sweet, mild, melon-like. Eat like an apple — no astringency.', chillHours: '200-400', harvestWindow: 'October-November', pollination: 'Self-fertile (sometimes)', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 7, zoneMax: 10, matureHeight: '4-6m / 12-20ft', growthHabit: 'spreading', perennialYears: 4, companionPlants: ['Comfrey', 'Clover', 'Nasturtium'], incompatiblePlants: [], commonPests: ['Persimmon borer', 'mealy bugs', 'birds'], careNotes: 'Non-astringent — can be eaten firm. Vigorous, productive tree. Attractive dark green foliage.' },
  { commonName: 'Wonderful Pomegranate', scientificName: 'Punica granatum', variety: 'Wonderful', family: 'Lythraceae', category: 'fruit', description: 'The most widely planted commercial pomegranate. Large, reddish-purple fruit with deep red arils. Sweet-tart, highly aromatic.', chillHours: '150-200', harvestWindow: 'September-October', pollination: 'Self-fertile', sunlight: 'full sun', waterNeeds: 'low', zoneMin: 7, zoneMax: 10, matureHeight: '3-4m / 10-13ft', growthHabit: 'shrub', perennialYears: 4, companionPlants: ['Comfrey', 'Clover', 'Nasturtium'], incompatiblePlants: [], commonPests: ['Pomegranate butterfly', 'alkaline-induced chlorosis'], careNotes: 'Drought-tolerant but fruits best with regular watering. Long-lived shrub. ornamental value too.' },
  { commonName: 'Concord Grape', scientificName: 'Vitis labrusca', variety: 'Concord', family: 'Vitaceae', category: 'fruit', description: 'The classic American grape. Blue-black, slipskin, sweet. Iconic grape jelly flavor. Excellent for fresh eating, juice, jelly, and wine.', chillHours: '800-1000', harvestWindow: 'September-October', pollination: 'Self-fertile', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 4, zoneMax: 8, matureHeight: '3-5m / 10-16ft', growthHabit: 'climbing', perennialYears: 3, companionPlants: ['Chives', 'Garlic', 'Borage', 'Sage'], incompatiblePlants: ['Cabbage', 'Radish', 'Radish'], commonPests: ['Grape berry moth', 'Japanese beetle', 'powdery mildew', 'black rot'], careNotes: 'Needs annual pruning to stay productive. Protect from birds. Great for arbor or trellis.' },
  { commonName: 'Thompson Seedless Grape', scientificName: 'Vitis vinifera', variety: 'Thompson Seedless', family: 'Vitaceae', category: 'fruit', description: 'The classic green seedless grape. Sweet, crisp, pale green berries. Excellent for fresh eating, raisins, and wine.', chillHours: '200-400', harvestWindow: 'August-September', pollination: 'Self-fertile', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 6, zoneMax: 9, matureHeight: '3-5m / 10-16ft', growthHabit: 'climbing', perennialYears: 3, companionPlants: ['Chives', 'Garlic', 'Borage', 'Sage'], incompatiblePlants: ['Cabbage', 'Radish'], commonPests: ['Grape berry moth', 'Japanese beetle', 'powdery mildew'], careNotes: 'Needs long, warm growing season for best sweetness. Good for raisin production. Train to wire trellis.' },
  { commonName: 'Hayward Kiwi', scientificName: 'Actinidia deliciosa', variety: 'Hayward', family: 'Actinidiaceae', category: 'fruit', description: 'The standard green kiwi. Large, fuzzy, oval fruit with bright green flesh. Sweet-tart, aromatic. Excellent fresh eating.', chillHours: '600-800', harvestWindow: 'October-November', pollination: 'Requires pollinizer (male Tomuri)', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 7, zoneMax: 9, matureHeight: '5-8m / 16-26ft', growthHabit: 'climbing', perennialYears: 5, companionPlants: ['Comfrey', 'Clover', 'Borage'], incompatiblePlants: [], commonPests: ['Kiwi vine moth', 'Pseudomonas', 'birds'], careNotes: 'Needs male pollinizer (1 male per 8 females). Very vigorous vine — give strong support. Fuzzy skin — peel before eating.' },

  // ── VEGETABLES — Nightshades ───────────────────────────────────────────────
  { commonName: 'Cherokee Purple Tomato', scientificName: 'Solanum lycopersicum', variety: 'Cherokee Purple', family: 'Solanaceae', category: 'vegetable', description: 'Heirloom beefsteak with dusky rose-purple skin. Rich, sweet, complex flavor. One of the best-tasting heirlooms.', harvestWindow: 'July-September', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 5, zoneMax: 10, matureHeight: '1.5-2m / 5-6ft', growthHabit: 'upright', perennialYears: 0, companionPlants: ['Basil', 'Carrot', 'Marigold', 'Parsley'], incompatiblePlants: ['Fennel', 'Brassicas (some)'], commonPests: ['Hornworm', 'aphids', 'late blight'], careNotes: 'Indeterminate — needs staking. Prone to cracking. Excellent fresh or for sandwiches.' },
  { commonName: 'Brandywine Tomato', scientificName: 'Solanum lycopersicum', variety: 'Brandywine', family: 'Solanaceae', category: 'vegetable', description: 'Legendary heirloom beefsteak. Pinkish-red, very meaty with intense sweet flavor. The standard for tomato taste.', harvestWindow: 'July-September', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 5, zoneMax: 10, matureHeight: '1.5-2.5m / 5-8ft', growthHabit: 'upright', perennialYears: 0, companionPlants: ['Basil', 'Carrot', 'Marigold', 'Parsley'], incompatiblePlants: ['Fennel', 'Brassicas (some)'], commonPests: ['Hornworm', 'aphids', 'late blight'], careNotes: 'Indeterminate, vigorous. Potato-leaf foliage. Low acid. Takes 80+ days to ripen — start early.' },
  { commonName: 'Sun Gold Tomato', scientificName: 'Solanum lycopersicum', variety: 'Sun Gold', family: 'Solanaceae', category: 'vegetable', description: 'Tiny orange cherry tomato with explosive sweetness. Exceptionally delicious. Vines produce thousands of fruits all season.', harvestWindow: 'June-October', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 5, zoneMax: 10, matureHeight: '2-3m / 6-10ft', growthHabit: 'vining', perennialYears: 0, companionPlants: ['Basil', 'Carrot', 'Marigold', 'Parsley'], incompatiblePlants: ['Fennel', 'Brassicas (some)'], commonPests: ['Aphids', 'whitefly', 'early blight'], careNotes: 'Indeterminate and very vigorous. Fruits are prone to cracking — harvest frequently. The sweetest tomato.' },
  { commonName: 'Roma Tomato', scientificName: 'Solanum lycopersicum', variety: 'Roma', family: 'Solanaceae', category: 'vegetable', description: 'Plum tomato with meaty, dense flesh. Few seeds, low moisture. The standard for paste, sauce, and canning.', harvestWindow: 'July-September', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 5, zoneMax: 10, matureHeight: '1.5m / 5ft', growthHabit: 'bush', perennialYears: 0, companionPlants: ['Basil', 'Carrot', 'Marigold', 'Parsley'], incompatiblePlants: ['Fennel', 'Brassicas (some)'], commonPests: ['Hornworm', 'aphids', 'late blight'], careNotes: 'Determinate — compact bush, less staking needed. Heavy producer of paste-sized fruits.' },
  { commonName: 'Beefsteak Tomato', scientificName: 'Solanum lycopersicum', variety: 'Beefsteak', family: 'Solanaceae', category: 'vegetable', description: 'Massive slicing tomato — can weigh over 1 lb. Pink-red, very meaty. Classic for burgers and sandwiches.', harvestWindow: 'July-September', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 5, zoneMax: 10, matureHeight: '1.5-2m / 5-6ft', growthHabit: 'upright', perennialYears: 0, companionPlants: ['Basil', 'Carrot', 'Marigold', 'Parsley'], incompatiblePlants: ['Fennel', 'Brassicas (some)'], commonPests: ['Hornworm', 'cracking', 'blossom end rot'], careNotes: 'Indeterminate. Needs strong staking. Keep evenly watered to prevent blossom end rot.' },
  { commonName: 'San Marzano Tomato', scientificName: 'Solanum lycopersicum', variety: 'San Marzano', family: 'Solanaceae', category: 'vegetable', description: 'Italian heirloom plum tomato. Elongated fruits with thick flesh and few seeds. The gold standard for Neapolitan pizza sauce.', harvestWindow: 'July-September', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 5, zoneMax: 10, matureHeight: '1.5-2m / 5-6ft', growthHabit: 'upright', perennialYears: 0, companionPlants: ['Basil', 'Carrot', 'Marigold', 'Parsley'], incompatiblePlants: ['Fennel', 'Brassicas (some)'], commonPests: ['Hornworm', 'aphids', 'late blight'], careNotes: 'Indeterminate. Lower acid than Romas. Wait for full ripeness — very worth the wait for sauce.' },
  { commonName: 'Yellow Pear Tomato', scientificName: 'Solanum lycopersicum', variety: 'Yellow Pear', family: 'Solanaceae', category: 'vegetable', description: 'Small, pear-shaped, bright yellow cherry tomato. Mild, sweet flavor. Very productive — bears hundreds of tiny fruits.', harvestWindow: 'June-October', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 5, zoneMax: 10, matureHeight: '2-3m / 6-10ft', growthHabit: 'vining', perennialYears: 0, companionPlants: ['Basil', 'Carrot', 'Marigold', 'Parsley'], incompatiblePlants: ['Fennel', 'Brassicas (some)'], commonPests: ['Aphids', 'whitefly'], careNotes: 'Indeterminate and extremely vigorous. Great for kids — sweet and novelty shape. Reseeds readily.' },
  { commonName: 'Black Krim Tomato', scientificName: 'Solanum lycopersicum', variety: 'Black Krim', family: 'Solanaceae', category: 'vegetable', description: 'Ukrainian heirloom with dark mahogany-brown skin. Smoky, sweet, intense flavor. One of the best "black" tomatoes.', harvestWindow: 'July-September', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 5, zoneMax: 10, matureHeight: '1.5-2m / 5-6ft', growthHabit: 'upright', perennialYears: 0, companionPlants: ['Basil', 'Carrot', 'Marigold', 'Parsley'], incompatiblePlants: ['Fennel'], commonPests: ['Hornworm', 'cracking', 'late blight'], careNotes: 'Indeterminate. Color best in heat. Skin can crack — harvest promptly. Rich, smoky flavor.' },
  { commonName: 'California Wonder Pepper', scientificName: 'Capsicum annuum', variety: 'California Wonder', family: 'Solanaceae', category: 'vegetable', description: 'Classic bell pepper. Large, blocky, thick-walled fruits. Green → red when ripe. Sweet and mild.', harvestWindow: 'July-September', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 5, zoneMax: 10, matureHeight: '60-90cm / 2-3ft', growthHabit: 'upright', perennialYears: 0, companionPlants: ['Basil', 'Onion', 'Carrot', 'Marjoram'], incompatiblePlants: ['Fennel'], commonPests: ['Aphids', 'pepper weevil', 'blossom end rot'], careNotes: 'Needs warm soil to get started. Green fruits can be picked early; leave on plant to ripen red for more sweetness.' },
  { commonName: 'Jalapeño Pepper', scientificName: 'Capsicum annuum', variety: 'Jalapeño', family: 'Solanaceae', category: 'vegetable', description: 'Medium heat chili, 2,500-8,000 Scoville. Dark green maturing to red. Classic Mexican pepper for salsas, nachos, and smoked chipotle.', harvestWindow: 'July-September', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 5, zoneMax: 10, matureHeight: '60-90cm / 2-3ft', growthHabit: 'upright', perennialYears: 0, companionPlants: ['Basil', 'Onion', 'Carrot', 'Tomato'], incompatiblePlants: ['Fennel'], commonPests: ['Aphids', 'pepper weevil'], careNotes: 'Harvest green for classic jalapeño flavor, or leave to ripen red for sweeter, smokier notes. Productive.' },
  { commonName: 'Poblano Pepper', scientificName: 'Capsicum annuum', variety: 'Poblano', family: 'Solanaceae', category: 'vegetable', description: 'Large, mild chili (500-2,000 Scoville). Dark green, heart-shaped. When dried, called Ancho — central to Mexican mole.', harvestWindow: 'July-September', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 5, zoneMax: 10, matureHeight: '60-90cm / 2-3ft', growthHabit: 'upright', perennialYears: 0, companionPlants: ['Basil', 'Onion', 'Carrot', 'Tomato'], incompatiblePlants: ['Fennel'], commonPests: ['Aphids', 'pepper weevil'], careNotes: 'Mild heat when fresh (poblano). Ancho when dried. Large plants — give space. Great for stuffing.' },
  { commonName: 'Shishito Pepper', scientificName: 'Capsicum annuum', variety: 'Shishito', family: 'Solanaceae', category: 'vegetable', description: 'Japanese heirloom chili. Thin-walled, slightly crinkled. Mild heat (500-2,500 Scoville) — about 1 in 10 is hot. Excellent blistered or grilled.', harvestWindow: 'July-September', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 5, zoneMax: 10, matureHeight: '60-90cm / 2-3ft', growthHabit: 'upright', perennialYears: 0, companionPlants: ['Basil', 'Onion', 'Carrot', 'Tomato'], incompatiblePlants: ['Fennel'], commonPests: ['Aphids', 'pepper weevil'], careNotes: 'Harvest small (2-3") for best flavor. Blister in hot pan with oil — delicious with sea salt. Very productive.' },

  // ── VEGETABLES — Brassicas & Greens ──────────────────────────────────────
  { commonName: 'Lacinato Kale', scientificName: 'Brassica oleracea var. sabellica', variety: 'Lacinato', family: 'Brassicaceae', category: 'vegetable', description: 'Italian heirloom aka "Dinosaur Kale." Dark blue-green, heavily savoyed leaves. Sweeter and more delicate than curly kale. Excellent for soups and chips.', harvestWindow: 'March-November (cut-and-come-again)', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 2, zoneMax: 10, matureHeight: '60-90cm / 2-3ft', growthHabit: 'upright', perennialYears: 0, companionPlants: ['Beet', 'Celery', 'Onion', 'Chamomile', 'Dill'], incompatiblePlants: ['Strawberry'], commonPests: ['Cabbage worm', 'aphids', 'flea beetle'], careNotes: 'Frost improves flavor. Cut outer leaves first. Can overwinter in mild climates.' },
  { commonName: 'Rainbow Chard', scientificName: 'Beta vulgaris', variety: 'Rainbow', family: 'Amaranthaceae', category: 'vegetable', description: 'Stunning mix of red, orange, yellow, and white stemmed chard. Mild, earthy flavor. Excellent for fresh eating and cooking.', harvestWindow: 'May-October', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 3, zoneMax: 10, matureHeight: '45-60cm / 18-24in', growthHabit: 'upright', perennialYears: 0, companionPlants: ['Bean', 'Cabbage', 'Onion', 'Lettuce'], incompatiblePlants: [], commonPests: ['Leaf miner', 'aphids', 'slugs'], careNotes: 'Cut-and-come-again. Pick outer leaves first. Overwinters in mild climates. Beautiful in ornamental beds.' },
  { commonName: 'Brussels Sprouts', scientificName: 'Brassica oleracea var. gemmifera', variety: 'Long Island', family: 'Brassicaceae', category: 'vegetable', description: 'Classic heirloom Brussels sprout. Compact plants produce 50-100 small, tight sprouts along the stem. Sweet after frost.', harvestWindow: 'September-March', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 3, zoneMax: 9, matureHeight: '60-90cm / 2-3ft', growthHabit: 'upright', perennialYears: 0, companionPlants: ['Beet', 'Celery', 'Onion', 'Chamomile', 'Dill', 'Thyme'], incompatiblePlants: ['Strawberry', 'Tomato'], commonPests: ['Cabbage worm', 'aphids', 'flea beetle', 'cabbage maggot'], careNotes: 'Long growing season — start early. Remove lower leaves as sprouts develop. Frost makes them sweeter.' },
  { commonName: 'Purple Cauliflower', scientificName: 'Brassica oleracea var. botrytis', variety: 'Purple', family: 'Brassicaceae', category: 'vegetable', description: 'Striking deep purple cauliflower. Turns bright green when cooked. Mild, sweet, nutty flavor. No need to blanch like white varieties.', harvestWindow: 'June-August', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 3, zoneMax: 10, matureHeight: '60-75cm / 2-2.5ft', growthHabit: 'upright', perennialYears: 0, companionPlants: ['Beet', 'Celery', 'Onion', 'Chamomile'], incompatiblePlants: ['Strawberry', 'Tomato'], commonPests: ['Cabbage worm', 'aphids', 'flea beetle'], careNotes: 'Heat-tolerant compared to white cauliflower. Color is natural anthocyanin — antioxidant. Harvest at 6-8" diameter.' },
  { commonName: 'Romanesco Broccoli', scientificName: 'Brassica oleracea var. botrytis', variety: 'Romanesco', family: 'Brassicaceae', category: 'vegetable', description: 'Fractal, logarithmic spiral head in lime green. Nutty, mild, less sulfurous than regular broccoli. One of the most beautiful vegetables.', harvestWindow: 'April-June, September-October', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 3, zoneMax: 10, matureHeight: '60-90cm / 2-3ft', growthHabit: 'upright', perennialYears: 0, companionPlants: ['Beet', 'Celery', 'Onion', 'Chamomile', 'Dill'], incompatiblePlants: ['Strawberry', 'Tomato'], commonPests: ['Cabbage worm', 'aphids', 'flea beetle'], careNotes: 'Two seasons — spring and fall. Pick when head is compact, before yellow flowers appear. Side shoots continue producing.' },
  { commonName: 'Bok Choy', scientificName: 'Brassica rapa subsp. chinensis', variety: 'Toy Choy', family: 'Brassicaceae', category: 'vegetable', description: 'Compact, dwarf bok choy with tender white stems and dark green leaves. Quick growing, mild, sweet. Great for stir-fries and fresh eating.', harvestWindow: 'March-June, September-November', sunlight: 'partial shade', waterNeeds: 'moderate', zoneMin: 3, zoneMax: 10, matureHeight: '25-30cm / 10-12in', growthHabit: 'rosette', perennialYears: 0, companionPlants: ['Chives', 'Onion', 'Garlic', 'Nasturtium'], incompatiblePlants: [], commonPests: ['Cabbage worm', 'flea beetle', 'aphids'], careNotes: 'Quick crop — ready in 30-50 days. Best in cool weather. Bolt-resistant varieties for spring.' },
  { commonName: 'Napa Cabbage', scientificName: 'Brassica rapa subsp. pekinensis', variety: 'Napa', family: 'Brassicaceae', category: 'vegetable', description: 'Elongated, barrel-shaped cabbage with crisp, tender leaves. Mild, slightly sweet. Essential for kimchi and Asian slaws.', harvestWindow: 'April-June, September-November', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 3, zoneMax: 10, matureHeight: '30-45cm / 12-18in', growthHabit: 'bunching', perennialYears: 0, companionPlants: ['Beet', 'Celery', 'Onion', 'Chamomile'], incompatiblePlants: ['Strawberry', 'Tomato'], commonPests: ['Cabbage worm', 'aphids', 'flea beetle'], careNotes: 'Cool-weather crop. Excellent for kimchi fermentation. Harvest when heads are firm.' },
  { commonName: 'Tatsoi', scientificName: 'Brassica rapa subsp. rosularis', variety: 'Tatsoi', family: 'Brassicaceae', category: 'vegetable', description: 'Low-growing rosette with small, dark green, spoon-shaped leaves. Mild mustard flavor. Extremely cold-hardy.', harvestWindow: 'March-December', sunlight: 'partial shade', waterNeeds: 'moderate', zoneMin: 3, zoneMax: 10, matureHeight: '15-20cm / 6-8in', growthHabit: 'rosette', perennialYears: 0, companionPlants: ['Chives', 'Onion', 'Garlic', 'Nasturtium'], incompatiblePlants: [], commonPests: ['Cabbage worm', 'flea beetle', 'slugs'], careNotes: 'One of the hardiest Asian greens. Sweetens with frost. Cut-and-come-again harvest.' },
  { commonName: 'Astro Arugula', scientificName: 'Eruca vesicaria', variety: 'Astro', family: 'Brassicaceae', category: 'vegetable', description: 'Mild arugula with less peppery bite than wild types. Fast-growing, heat-tolerant. Nutty, slightly sweet with peppery finish.', harvestWindow: 'April-November', sunlight: 'partial shade', waterNeeds: 'moderate', zoneMin: 3, zoneMax: 10, matureHeight: '20-30cm / 8-12in', growthHabit: 'rosette', perennialYears: 0, companionPlants: ['Radish', 'Lettuce', 'Pea', 'Spinach'], incompatiblePlants: ['Strawberry'], commonPests: ['Flea beetle', 'cabbage worm', 'aphids'], careNotes: 'Bolt-resistant. Harvest outer leaves or cut whole plant. succession plant every 2-3 weeks.' },
  { commonName: 'Bloomsdale Spinach', scientificName: 'Spinacia oleracea', variety: 'Bloomsdale', family: 'Amaranthaceae', category: 'vegetable', description: 'Heirloom spinach with savoyed, dark green leaves. Excellent flavor, tender texture. Very cold-hardy.', harvestWindow: 'March-June, September-November', sunlight: 'partial shade', waterNeeds: 'moderate', zoneMin: 3, zoneMax: 8, matureHeight: '25-30cm / 10-12in', growthHabit: 'rosette', perennialYears: 0, companionPlants: ['Strawberry', 'Pea', 'Cabbage', 'Radish', 'Bean'], incompatiblePlants: [], commonPests: ['Leaf miner', 'downy mildew', 'slugs'], careNotes: 'Plant early spring or fall. Bolts in heat. Excellent for fall/winter in mild climates.' },
  { commonName: 'Georgia Southern Collards', scientificName: 'Brassica oleracea var. viridis', variety: 'Georgia Southern', family: 'Brassicaceae', category: 'vegetable', description: 'Classic Southern collard. Large, smooth, blue-green leaves. Sweeter after frost. Extremely heat and cold tolerant.', harvestWindow: 'Year-round (peaks cool weather)', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 6, zoneMax: 10, matureHeight: '60-90cm / 2-3ft', growthHabit: 'upright', perennialYears: 0, companionPlants: ['Beet', 'Onion', 'Thyme', 'Nasturtium'], incompatiblePlants: [], commonPests: ['Cabbage worm', 'aphids', 'flea beetle'], careNotes: 'Cut outer leaves for cut-and-come-again. Plants can grow large (2-3 ft). Traditional in Southern US cuisine.' },
  { commonName: 'Mizuna', scientificName: 'Brassica rapa subsp. japonica', variety: 'Mizuna', family: 'Brassicaceae', category: 'vegetable', description: 'Japanese mustard green with deeply cut, frilly leaves. Mild, peppery, mustard flavor. Excellent for salads and stir-fries.', harvestWindow: 'March-December', sunlight: 'partial shade', waterNeeds: 'moderate', zoneMin: 4, zoneMax: 10, matureHeight: '20-30cm / 8-12in', growthHabit: 'rosette', perennialYears: 0, companionPlants: ['Chives', 'Onion', 'Garlic', 'Nasturtium'], incompatiblePlants: [], commonPests: ['Flea beetle', 'cabbage worm', 'aphids'], careNotes: 'Fast growing, heat and cold tolerant. Cut-and-come-again. Adds spicy zip to salads.' },

  // ── VEGETABLES — Root & Alliums ────────────────────────────────────────────
  { commonName: 'Marketmore Cucumber', scientificName: 'Cucumis sativus', variety: 'Marketmore', family: 'Cucurbitaceae', category: 'vegetable', description: 'Slicing cucumber with dark green skin, 20-25cm long. Crisp, tender flesh with mild flavor. Productive and disease-resistant.', harvestWindow: 'July-September', sunlight: 'full sun', waterNeeds: 'high', zoneMin: 4, zoneMax: 10, matureHeight: '30-40cm / 12-16in (vine 1.5-2m)', growthHabit: 'vining', perennialYears: 0, companionPlants: ['Bean', 'Corn', 'Pea', 'Radish', 'Dill', 'Marigold'], incompatiblePlants: ['Potato', 'Aromatic herbs (close)'], commonPests: ['Cucumber beetle', 'powdery mildew', 'aphids'], careNotes: 'Train on trellis for straighter fruit. Harvest frequently for continued production.' },
  { commonName: 'Lemon Cucumber', scientificName: 'Cucumis sativus', variety: 'Lemon', family: 'Cucurbitaceae', category: 'vegetable', description: 'Unique round, lemon-yellow cucumber. Crisp, mild, never bitter. Novelty that kids love. Excellent fresh eating.', harvestWindow: 'July-September', sunlight: 'full sun', waterNeeds: 'high', zoneMin: 4, zoneMax: 10, matureHeight: '30-40cm / 12-16in (vine 1.5-2m)', growthHabit: 'vining', perennialYears: 0, companionPlants: ['Bean', 'Corn', 'Pea', 'Radish', 'Dill'], incompatiblePlants: ['Potato'], commonPests: ['Cucumber beetle', 'powdery mildew'], careNotes: 'Harvest when pale yellow — over-ripening makes it seedy. Vines are productive all season.' },
  { commonName: 'Boston Pickling Cucumber', scientificName: 'Cucumis sativus', variety: 'Boston Pickling', family: 'Cucurbitaceae', category: 'vegetable', description: 'Classic pickling cucumber. Small (3-5"), blocky, firm. Prolific producer. The traditional cuke for kosher dills.', harvestWindow: 'July-September', sunlight: 'full sun', waterNeeds: 'high', zoneMin: 4, zoneMax: 10, matureHeight: '30-40cm / 12-16in (vine 1.5-2m)', growthHabit: 'vining', perennialYears: 0, companionPlants: ['Bean', 'Corn', 'Pea', 'Radish', 'Dill', 'Marigold'], incompatiblePlants: ['Potato', 'Aromatic herbs (close)'], commonPests: ['Cucumber beetle', 'powdery mildew', 'aphids'], careNotes: 'Harvest small (2-4") for cornichons. Pick daily for steady supply. Vines resist scab.' },
  { commonName: 'Butternut Squash', scientificName: 'Cucurbita moschata', variety: 'Butternut', family: 'Cucurbitaceae', category: 'vegetable', description: 'Tan, bell-shaped winter squash with sweet, orange flesh. Excellent keeper — stores for months. Versatile for roasting, soup, baking.', harvestWindow: 'September-October', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 3, zoneMax: 10, matureHeight: '45-60cm / 18-24in (vine 3-5m)', growthHabit: 'trailing', perennialYears: 0, companionPlants: ['Corn', 'Bean', 'Nasturtium', 'Marigold', 'Borage'], incompatiblePlants: ['Potato'], commonPests: ['Squash vine borer', 'powdery mildew', 'cucumber beetle'], careNotes: 'Cure in sun for 10-14 days before storage. Stores 3-6 months in cool, dry place. Very nutritious.' },
  { commonName: 'Delicata Squash', scientificName: 'Cucurbita pepo', variety: 'Delicata', family: 'Cucurbitaceae', category: 'vegetable', description: 'Small, oblong winter squash with cream and green striped skin. Sweet, smooth flesh — no peeling needed. Roasted, it tastes like sweet potato.', harvestWindow: 'September-October', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 3, zoneMax: 10, matureHeight: '45-60cm / 18-24in (vine 2-3m)', growthHabit: 'trailing', perennialYears: 0, companionPlants: ['Corn', 'Bean', 'Nasturtium', 'Marigold', 'Borage'], incompatiblePlants: ['Potato'], commonPests: ['Squash vine borer', 'powdery mildew', 'cucumber beetle'], careNotes: 'Short storage (2-3 months). Thin skin is edible when roasted. Very popular for its convenience and flavor.' },
  { commonName: 'Acorn Squash', scientificName: 'Cucurbita pepo', variety: 'Acorn', family: 'Cucurbitaceae', category: 'vegetable', description: 'Small, ribbed dark green (sometimes orange) winter squash. Sweet, slightly fibrous orange flesh. Good keeper.', harvestWindow: 'September-October', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 3, zoneMax: 10, matureHeight: '45-60cm / 18-24in (vine 2-3m)', growthHabit: 'trailing', perennialYears: 0, companionPlants: ['Corn', 'Bean', 'Nasturtium', 'Marigold'], incompatiblePlants: ['Potato'], commonPests: ['Squash vine borer', 'powdery mildew', 'cucumber beetle'], careNotes: 'Stores well (1-3 months). Cut in half and bake for a simple, warming side dish.' },
  { commonName: 'Spaghetti Squash', scientificName: 'Cucurbita pepo', variety: 'Spaghetti', family: 'Cucurbitaceae', category: 'vegetable', description: 'Yellow, oval winter squash. When cooked, flesh shreds into spaghetti-like strands. Low calorie, mild. Great keto pasta substitute.', harvestWindow: 'September-October', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 3, zoneMax: 10, matureHeight: '45-60cm / 18-24in (vine 3-5m)', growthHabit: 'trailing', perennialYears: 0, companionPlants: ['Corn', 'Bean', 'Nasturtium', 'Marigold'], incompatiblePlants: ['Potato'], commonPests: ['Squash vine borer', 'powdery mildew', 'cucumber beetle'], careNotes: 'Harvest when skin is fully yellow and hard. Cut in half, remove seeds, roast or microwave. Fork-pull flesh into strands.' },
  { commonName: 'Yellow Crookneck Squash', scientificName: 'Cucurbita pepo', variety: 'Yellow Crookneck', family: 'Cucurbitaceae', category: 'vegetable', description: 'Classic summer squash with curved neck and golden-yellow skin. Nutty, sweet flavor. Best picked small (4-6").', harvestWindow: 'June-September', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 3, zoneMax: 10, matureHeight: '45-60cm / 18-24in (vine 1-2m)', growthHabit: 'bush', perennialYears: 0, companionPlants: ['Corn', 'Bean', 'Nasturtium', 'Marigold', 'Radish'], incompatiblePlants: ['Potato'], commonPests: ['Squash vine borer', 'powdery mildew', 'cucumber beetle'], careNotes: 'Harvest young (4-6") for best flavor — skin should be tender, not waxy. Check daily during peak.' },
  { commonName: 'Black Beauty Zucchini', scientificName: 'Cucurbita pepo', variety: 'Black Beauty', family: 'Cucurbitaceae', category: 'vegetable', description: 'Classic dark green zucchini. Glossy, cylindrical fruits. Compact bush. Very productive — the standard home garden zucchini.', harvestWindow: 'June-September', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 3, zoneMax: 10, matureHeight: '45-60cm / 18-24in', growthHabit: 'bush', perennialYears: 0, companionPlants: ['Corn', 'Bean', 'Nasturtium', 'Marigold', 'Radish'], incompatiblePlants: ['Potato'], commonPests: ['Squash vine borer', 'powdery mildew', 'cucumber beetle'], careNotes: 'Harvest at 6-8" for best texture. One plant usually produces 5-10 lbs. Check daily during peak.' },
  { commonName: 'Sugar Snap Pea', scientificName: 'Pisum sativum', variety: 'Sugar Snap', family: 'Fabaceae', category: 'vegetable', description: 'Sweet, crisp peas you eat pod and all. Edible-podded snow pea × snap pea cross. Excellent fresh and in stir-fries.', harvestWindow: 'April-June', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 3, zoneMax: 8, matureHeight: '1.5-2m / 5-6ft', growthHabit: 'climbing', perennialYears: 0, companionPlants: ['Carrot', 'Radish', 'Turnip', 'Lettuce', 'Spinach', 'Cucumber', 'Bean'], incompatiblePlants: ['Onion', 'Garlic', 'Leek', 'Fennel'], commonPests: ['Pea aphid', 'powdery mildew', 'root rot'], careNotes: 'Plant early — peas love cool weather. Provide trellis or netting. Harvest when pods are plump but still crisp.' },

  // ── HERBS ─────────────────────────────────────────────────────────────────
  { commonName: 'Genovese Basil', scientificName: 'Ocimum basilicum', variety: 'Genovese', family: 'Lamiaceae', category: 'herb', description: 'The classic Italian basil for pesto. Large, glossy leaves with intense sweet aroma. The standard for Caprese and pesto genovese.', harvestWindow: 'June-September', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 5, zoneMax: 10, matureHeight: '45-60cm / 18-24in', growthHabit: 'upright', perennialYears: 0, companionPlants: ['Tomato', 'Pepper', 'Oregano', 'Asparagus', 'Marigold'], incompatiblePlants: ['Rue', 'Sage'], commonPests: ['Japanese beetle', 'aphids', 'downy mildew'], careNotes: 'Pinch flowers to prolong harvest. Harvest from top down. Sensitive to cold — plant after last frost.' },
  { commonName: 'Thai Basil', scientificName: 'Ocimum basilicum', variety: 'Thai', family: 'Lamiaceae', category: 'herb', description: 'Distinctive anise-clove flavor. Darker leaves with purple stems. Essential in Thai curries, Vietnamese pho. Heat-tolerant and slow to bolt.', harvestWindow: 'June-September', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 5, zoneMax: 10, matureHeight: '30-45cm / 12-18in', growthHabit: 'upright', perennialYears: 0, companionPlants: ['Tomato', 'Eggplant', 'Pepper'], incompatiblePlants: ['Rue'], commonPests: ['Japanese beetle', 'aphids'], careNotes: 'More heat-tolerant than sweet basil. Purple flowers are edible — great garnish. The definitive basil for Asian cooking.' },
  { commonName: 'Holy Basil (Tulsi)', scientificName: 'Ocimum tenuiflorum', variety: 'Holy (Tulsi)', family: 'Lamiaceae', category: 'herb', description: 'Sacred Hindu basil with peppery, clove-like aroma. Highly aromatic. Used in teas, Thai cooking, and Ayurvedic medicine.', harvestWindow: 'June-September', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 5, zoneMax: 10, matureHeight: '45-60cm / 18-24in', growthHabit: 'upright', perennialYears: 0, companionPlants: ['Tomato', 'Pepper'], incompatiblePlants: ['Rue'], commonPests: ['Japanese beetle', 'aphids'], careNotes: 'Can be grown as perennial in frost-free areas. Blooms attract pollinators. Tea from leaves is calming.' },
  { commonName: 'Tuscan Blue Rosemary', scientificName: 'Salvia rosmarinus', variety: 'Tuscan Blue', family: 'Lamiaceae', category: 'herb', description: 'Upright, vigorous rosemary with intense aroma. Darker blue flowers. Excellent for cooking and as an ornamental. Very drought-tolerant.', harvestWindow: 'Year-round', sunlight: 'full sun', waterNeeds: 'low', zoneMin: 7, zoneMax: 10, matureHeight: '1-2m / 3-6ft', growthHabit: 'upright', perennialYears: 3, companionPlants: ['Cabbage', 'Bean', 'Sage', 'Lavender', 'Thyme'], incompatiblePlants: ['Cucumber', 'Pumpkin', 'Mint (planted close)'], commonPests: ['Powdery mildew', 'spider mites', 'root rot'], careNotes: 'Mediterranean — needs well-drained soil, not too much water. Protect from hard freeze.' },
  { commonName: 'English Thyme', scientificName: 'Thymus vulgaris', variety: 'English', family: 'Lamiaceae', category: 'herb', description: 'Classic culinary thyme. Small, aromatic leaves with warm, slightly minty flavor. Essential in French cooking. Evergreen perennial.', harvestWindow: 'Year-round (peak summer)', sunlight: 'full sun', waterNeeds: 'low', zoneMin: 5, zoneMax: 9, matureHeight: '20-30cm / 8-12in', growthHabit: 'spreading', perennialYears: 3, companionPlants: ['Cabbage', 'Tomato', 'Eggplant', 'Strawberry', 'Rose'], incompatiblePlants: [], commonPests: ['Root rot (overwatering)', 'spider mites'], careNotes: 'Excellent ground cover. Drought-tolerant once established. Harvest regularly to keep compact shape.' },
  { commonName: 'Greek Oregano', scientificName: 'Origanum vulgare subsp. hirtum', variety: 'Greek', family: 'Lamiaceae', category: 'herb', description: 'The standard culinary oregano. Pungent, bold flavor essential for Greek salad, pizza, Italian dishes. White flowers attract pollinators.', harvestWindow: 'June-September', sunlight: 'full sun', waterNeeds: 'low', zoneMin: 5, zoneMax: 10, matureHeight: '30-60cm / 12-24in', growthHabit: 'spreading', perennialYears: 3, companionPlants: ['Tomato', 'Pepper', 'Cucumber', 'Squash'], incompatiblePlants: [], commonPests: ['Aphids (rare)', 'root rot'], careNotes: 'Cut back before flowering for best flavor. Spreads vigorously — give it space or contain in pot.' },
  { commonName: 'Common Sage', scientificName: 'Salvia officinalis', variety: 'Common', family: 'Lamiaceae', category: 'herb', description: 'Classic culinary sage. Velvety, gray-green leaves with earthy, slightly camphoraceous flavor. Essential for Thanksgiving stuffing.', harvestWindow: 'Year-round', sunlight: 'full sun', waterNeeds: 'low', zoneMin: 5, zoneMax: 9, matureHeight: '45-60cm / 18-24in', growthHabit: 'spreading', perennialYears: 3, companionPlants: ['Cabbage', 'Carrot', 'Rosemary', 'Bean', 'Pea'], incompatiblePlants: ['Onion', 'Garlic', 'Cucumber'], commonPests: ['Powdery mildew', 'slugs', 'spider mites'], careNotes: 'Woody perennial — prune back hard in spring to keep compact. Evergreen in mild winters.' },
  { commonName: 'Italian Flat Leaf Parsley', scientificName: 'Petroselinum crispum', variety: 'Italian Flat Leaf', family: 'Apiaceae', category: 'herb', description: 'Superior flavor to curly parsley. Flat, bright green leaves. Essential in Italian cooking, chimichurri, tabbouleh.Biennial.', harvestWindow: 'April-November', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 5, zoneMax: 9, matureHeight: '45-60cm / 18-24in', growthHabit: 'upright', perennialYears: 0, companionPlants: ['Tomato', 'Asparagus', 'Carrot', 'Chives'], incompatiblePlants: ['Mint (if in same bed)'], commonPests: ['Parsley worm (swallowtail)', 'aphids', 'leaf spot'], careNotes: 'Biennial — bolts second year. Slow to germinate (2-4 weeks). Cut outer stems first.' },
  { commonName: 'Santo Cilantro', scientificName: 'Coriandrum sativum', variety: 'Santo', family: 'Apiaceae', category: 'herb', description: 'Bolt-resistant cilantro. Produces leaves for longer in heat. Essential Mexican and Asian herb. Seeds are coriander.', harvestWindow: 'April-October', sunlight: 'partial shade', waterNeeds: 'moderate', zoneMin: 3, zoneMax: 10, matureHeight: '45-60cm / 18-24in', growthHabit: 'upright', perennialYears: 0, companionPlants: ['Tomato', 'Spinach', 'Pea', 'Bean', 'Pepper'], incompatiblePlants: ['Fennel'], commonPests: ['Aphids', 'leaf spot'], careNotes: 'Bolt-resistant means longer harvest window. Succession plant every 2-3 weeks for continuous supply.' },
  { commonName: 'Mammoth Dill', scientificName: 'Anethum graveolens', variety: 'Mammoth', family: 'Apiaceae', category: 'herb', description: 'Large, vigorous dill. Feathery foliage is excellent for fresh use, pickling. Large seed heads for pickling spice or ornamental use.', harvestWindow: 'May-September', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 3, zoneMax: 9, matureHeight: '90-120cm / 3-4ft', growthHabit: 'upright', perennialYears: 0, companionPlants: ['Cabbage', 'Cucumber', 'Onion', 'Lettuce', 'Bean'], incompatiblePlants: ['Carrot (some reports)', 'Fennel', 'Tomato (close)'], commonPests: ['Dill aphid', 'parsley worm', 'lacy bug'], careNotes: 'Let some plants flower for beneficial insects. Self-seeds readily. Leaves (dill weed) and seeds (dill seed) both useful.' },
  { commonName: 'Chives', scientificName: 'Allium schoenoprasum', variety: 'Chives', family: 'Amaryllidaceae', category: 'herb', description: 'Mild onion-flavored grass-like leaves. Edible purple flowers. Essential in French cuisine. Perennial — comes back every year.', harvestWindow: 'Year-round (peak spring-summer)', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 3, zoneMax: 9, matureHeight: '25-30cm / 10-12in', growthHabit: 'bunching', perennialYears: 3, companionPlants: ['Apple', 'Carrot', 'Tomato', 'Rose', 'Grape'], incompatiblePlants: ['Bean', 'Pea', 'Asparagus'], commonPests: ['Thrips', 'onion fly'], careNotes: 'Divide clumps every 2-3 years to keep productive. Flowers are edible — great in salads.' },
  { commonName: 'French Sorrel', scientificName: 'Rumex acetosa', variety: 'French', family: 'Polygonaceae', category: 'herb', description: 'Lemony, tangy perennial green. Large, arrow-shaped leaves. Excellent for salads, soups, and fish. Very productive.', harvestWindow: 'March-October', sunlight: 'partial shade', waterNeeds: 'moderate', zoneMin: 4, zoneMax: 9, matureHeight: '30-45cm / 12-18in', growthHabit: 'bunching', perennialYears: 3, companionPlants: ['Strawberry', 'Cabbage', 'Onion'], incompatiblePlants: [], commonPests: ['Slugs', 'leaf spot'], careNotes: 'Perennial — comes back for years. Harvest young leaves for mildest flavor.Oxalic acid — use moderately if prone to kidney stones.' },
  { commonName: 'Lemongrass', scientificName: 'Cymbopogon citratus', variety: 'Lemongrass', family: 'Poaceae', category: 'herb', description: 'Tropical grass with intensely lemon-scented stalks. Essential in Thai and Vietnamese cooking. Stalks add lemon flavor to teas, curries, soups.', harvestWindow: 'Year-round (frost-free)', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 9, zoneMax: 10, matureHeight: '90-120cm / 3-4ft', growthHabit: 'bunching', perennialYears: 0, companionPlants: ['Tomato', 'Basil', 'Garlic'], incompatiblePlants: [], commonPests: ['Spider mites (indoors)', 'rust'], careNotes: 'Grown as annual in cold climates. In zones 8+, leave roots in ground. Bring inside in pots for winter.' },
  { commonName: 'Borage', scientificName: 'Borago officinalis', variety: 'Borage', family: 'Boraginaceae', category: 'herb', description: 'Edible blue star-shaped flowers with cucumber flavor. Attracts bees and beneficial insects. Leaves can be cooked like greens or used fresh.', harvestWindow: 'May-September', sunlight: 'full sun', waterNeeds: 'low', zoneMin: 3, zoneMax: 10, matureHeight: '60-90cm / 2-3ft', growthHabit: 'bunching', perennialYears: 0, companionPlants: ['Tomato', 'Strawberry', 'Squash', 'Cucumber', 'Corn'], incompatiblePlants: [], commonPests: ['Few pests', 'slug damage to seedlings'], careNotes: 'Excellent bee plant — always surrounded by honeybees. Self-seeds aggressively. Companion to tomatoes and squash.' },
  { commonName: 'Nasturtium Jewel', scientificName: 'Tropaeolum majus', variety: 'Jewel', family: 'Tropaeolaceae', category: 'herb', description: 'Compact nasturtium with vibrant edible flowers and leaves. Peppery flavor. Excellent trap crop for aphids. Ornamental and edible.', harvestWindow: 'June-September', sunlight: 'full sun', waterNeeds: 'low', zoneMin: 4, zoneMax: 10, matureHeight: '30-40cm / 12-16in', growthHabit: 'trailing', perennialYears: 0, companionPlants: ['Cabbage', 'Tomato', 'Cucumber', 'Squash', 'Radish', 'Bean'], incompatiblePlants: [], commonPests: ['Aphids (attracts them away from crops)'], careNotes: 'Excellent trap crop — aphids prefer nasturtium. Plant near vulnerable crops. Flowers and leaves are edible with peppery taste.' },
  { commonName: 'Calendula Respel', scientificName: 'Calendula officinalis', variety: 'Respel', family: 'Asteraceae', category: 'herb', description: 'Hardy calendula with bright orange, edible petals. Used in salves and skin care. Petals add color to salads and rice. Also called pot marigold.', harvestWindow: 'May-October', sunlight: 'full sun', waterNeeds: 'moderate', zoneMin: 3, zoneMax: 10, matureHeight: '30-45cm / 12-18in', growthHabit: 'upright', perennialYears: 0, companionPlants: ['Tomato', 'Bean', 'Cucumber', 'Squash', 'Cabbage'], incompatiblePlants: [], commonPests: ['Aphids', 'powdery mildew'], careNotes: 'Self-seeds readily. Deadhead for more blooms. Petals are a saffron substitute — both color and mild flavor.' },
]

async function main() {
  console.log('[seed-varieties] Starting variety seed...\n')
  console.log(`[seed-varieties] Total varieties to process: ${VARIETIES.length}\n`)

  let created = 0
  let updated = 0
  let skipped = 0
  let errors = 0

  for (let i = 0; i < VARIETIES.length; i++) {
    const v = VARIETIES[i]
    try {
      // Check if record with this (scientificName, variety) already exists
      const existing = await prisma.plantEntry.findFirst({
        where: {
          scientificName: v.scientificName,
          variety: v.variety,
        },
      })

      const data = {
        commonName: v.commonName,
        scientificName: v.scientificName,
        variety: v.variety,
        category: v.category,
        family: v.family,
        description: v.description ?? null,
        chillHours: v.chillHours ?? null,
        harvestWindow: v.harvestWindow ?? null,
        pollination: v.pollination ?? null,
        sunlight: v.sunlight ?? null,
        waterNeeds: v.waterNeeds ?? null,
        zoneMin: v.zoneMin ?? null,
        zoneMax: v.zoneMax ?? null,
        matureHeight: v.matureHeight ?? null,
        growthHabit: v.growthHabit ?? null,
        perennialYears: v.perennialYears ?? null,
        companionPlants: v.companionPlants ?? null,
        incompatiblePlants: v.incompatiblePlants ?? null,
        commonPests: v.commonPests ?? null,
        careNotes: v.careNotes ?? null,
      }

      if (existing) {
        await prisma.plantEntry.update({
          where: { id: existing.id },
          data,
        })
        updated++
        if ((i + 1) % 20 === 0) process.stdout.write(`  — Updated: ${v.commonName}\n`)
      } else {
        await prisma.plantEntry.create({ data })
        created++
        if ((i + 1) % 20 === 0) process.stdout.write(`  ✓ Created: ${v.commonName}\n`)
      }
    } catch (err: any) {
      errors++
      console.error(`  ✗ Error [${v.commonName}]: ${err.message}`)
    }

    if ((i + 1) % 20 === 0) {
      process.stdout.write(`  Progress: ${i + 1}/${VARIETIES.length} | created: ${created} | updated: ${updated} | skipped: ${skipped} | errors: ${errors}\n`)
    }
  }

  console.log(`\n[seed-varieties] Done! Created: ${created} | Updated: ${updated} | Errors: ${errors}`)

  // Report total with variety set
  const count = await prisma.plantEntry.count({
    where: { variety: { not: null, equals: '' }, },
  })
  console.log(`[seed-varieties] Total records with variety set: ${count}`)

  await prisma.$disconnect()
}

main().catch(async (err) => {
  console.error('[seed-varieties] Fatal:', err)
  await prisma.$disconnect()
  process.exit(1)
})
